export const CARD_COMBINATION_RULES = [
  {
    ruleId: "r001",
    priority: 50,
    condition: { cards: [0, 1], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["new_beginning"],
      meaningModifier: "initiative_emerges",
    },
    aiModifier: { opportunity: 0.8 },
  },
  {
    ruleId: "r002",
    priority: 50,
    condition: { cards: [0, 10], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["unexpected_change"],
      meaningModifier: "fateful_start",
    },
    aiModifier: { opportunity: 0.75 },
  },
  {
    ruleId: "r003",
    priority: 60,
    condition: { cards: [0, 15], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["temptation", "risk"],
      meaningModifier: "naive_danger",
    },
    aiModifier: { risk: 0.85 },
  },
  {
    ruleId: "r004",
    priority: 70,
    condition: { cards: [0, 16], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["sudden_disruption"],
      meaningModifier: "reckless_collapse",
    },
    aiModifier: { risk: 0.9 },
  },
  {
    ruleId: "r005",
    priority: 50,
    condition: { cards: [1, 2], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["intuition", "strategy"],
      meaningModifier: "balanced_decision",
    },
    aiModifier: { clarity: 0.8 },
  },
  {
    ruleId: "r006",
    priority: 50,
    condition: { cards: [1, 3], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["creation"], meaningModifier: "manifesting_growth" },
    aiModifier: { opportunity: 0.85 },
  },
  {
    ruleId: "r007",
    priority: 60,
    condition: { cards: [1, 4], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["power"], meaningModifier: "authority_control" },
    aiModifier: { dominance: 0.8 },
  },
  {
    ruleId: "r008",
    priority: 50,
    condition: { cards: [1, 6], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["relationship_progress"],
      meaningModifier: "active_choice",
    },
    aiModifier: { relationship: 0.85 },
  },
  {
    ruleId: "r009",
    priority: 50,
    condition: { cards: [1, 7], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["momentum"], meaningModifier: "driven_success" },
    aiModifier: { success: 0.8 },
  },
  {
    ruleId: "r010",
    priority: 55,
    condition: { cards: [1, 9], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["inner_mastery"], meaningModifier: "wisdom_applied" },
    aiModifier: { clarity: 0.75 },
  },

  {
    ruleId: "r011",
    priority: 50,
    condition: { cards: [2, 9], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["deep_reflection"],
      meaningModifier: "hidden_understanding",
    },
    aiModifier: { clarity: 0.8 },
  },
  {
    ruleId: "r012",
    priority: 55,
    condition: { cards: [2, 14], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["balance", "intuition"],
      meaningModifier: "calm_perception",
    },
    aiModifier: { stability: 0.8 },
  },
  {
    ruleId: "r013",
    priority: 60,
    condition: { cards: [2, 18], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["uncertainty"],
      meaningModifier: "hidden_truth_emerges",
    },
    aiModifier: { risk: 0.7 },
  },
  {
    ruleId: "r014",
    priority: 50,
    condition: { cards: [2, 17], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["spiritual_guidance"],
      meaningModifier: "hopeful_intuition",
    },
    aiModifier: { hope: 0.85 },
  },
  {
    ruleId: "r015",
    priority: 55,
    condition: { cards: [3, 6], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["romance", "growth"],
      meaningModifier: "love_flourishes",
    },
    aiModifier: { relationship: 0.9 },
  },
  {
    ruleId: "r016",
    priority: 50,
    condition: { cards: [3, 10], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["fertility", "luck"],
      meaningModifier: "fortunate_growth",
    },
    aiModifier: { opportunity: 0.85 },
  },
  {
    ruleId: "r017",
    priority: 55,
    condition: { cards: [3, 19], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["joy", "abundance"],
      meaningModifier: "happy_success",
    },
    aiModifier: { success: 0.9 },
  },
  {
    ruleId: "r018",
    priority: 65,
    condition: { cards: [3, 15], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["indulgence"],
      meaningModifier: "excessive_attachment",
    },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r019",
    priority: 50,
    condition: { cards: [4, 5], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["institution"], meaningModifier: "structured_power" },
    aiModifier: { stability: 0.75 },
  },
  {
    ruleId: "r020",
    priority: 60,
    condition: { cards: [4, 16], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["authority_collapse"],
      meaningModifier: "power_structure_break",
    },
    aiModifier: { risk: 0.9 },
  },

  {
    ruleId: "r021",
    priority: 50,
    condition: { cards: [4, 7], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["strategic_victory"],
      meaningModifier: "disciplined_success",
    },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r022",
    priority: 55,
    condition: { cards: [4, 11], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["justice", "order"],
      meaningModifier: "fair_authority",
    },
    aiModifier: { stability: 0.85 },
  },
  {
    ruleId: "r023",
    priority: 55,
    condition: { cards: [5, 6], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["moral_choice"], meaningModifier: "belief_conflict" },
    aiModifier: { tension: 0.75 },
  },
  {
    ruleId: "r024",
    priority: 50,
    condition: { cards: [5, 9], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["spiritual_search"],
      meaningModifier: "seeking_guidance",
    },
    aiModifier: { clarity: 0.8 },
  },
  {
    ruleId: "r025",
    priority: 60,
    condition: { cards: [5, 20], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["awakening"], meaningModifier: "calling_realized" },
    aiModifier: { transformation: 0.9 },
  },
  {
    ruleId: "r026",
    priority: 50,
    condition: { cards: [6, 14], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["harmony"], meaningModifier: "balanced_union" },
    aiModifier: { relationship: 0.9 },
  },
  {
    ruleId: "r027",
    priority: 70,
    condition: { cards: [6, 15], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["toxic_attachment"],
      meaningModifier: "obsessive_relationship",
    },
    aiModifier: { risk: 0.9 },
  },
  {
    ruleId: "r028",
    priority: 50,
    condition: { cards: [6, 19], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["joyful_union"],
      meaningModifier: "happy_relationship",
    },
    aiModifier: { relationship: 0.95 },
  },
  {
    ruleId: "r029",
    priority: 60,
    condition: { cards: [7, 16], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["sudden_obstacle"],
      meaningModifier: "momentum_break",
    },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r030",
    priority: 50,
    condition: { cards: [7, 10], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["rapid_change"], meaningModifier: "accelerated_fate" },
    aiModifier: { opportunity: 0.8 },
  },

  {
    ruleId: "r031",
    priority: 50,
    condition: { cards: [7, 11], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["disciplined_power"],
      meaningModifier: "controlled_victory",
    },
    aiModifier: { success: 0.8 },
  },
  {
    ruleId: "r032",
    priority: 55,
    condition: { cards: [8, 15], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["temptation_conflict"],
      meaningModifier: "inner_struggle",
    },
    aiModifier: { risk: 0.85 },
  },
  {
    ruleId: "r033",
    priority: 50,
    condition: { cards: [8, 14], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["calm_strength"], meaningModifier: "gentle_control" },
    aiModifier: { stability: 0.8 },
  },
  {
    ruleId: "r034",
    priority: 50,
    condition: { cards: [8, 19], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["confidence"], meaningModifier: "bright_success" },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r035",
    priority: 60,
    condition: { cards: [9, 18], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["fear", "isolation"],
      meaningModifier: "confused_withdrawal",
    },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r036",
    priority: 50,
    condition: { cards: [9, 17], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["hope_after_reflection"],
      meaningModifier: "renewed_direction",
    },
    aiModifier: { hope: 0.85 },
  },
  {
    ruleId: "r037",
    priority: 55,
    condition: { cards: [9, 20], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["awakening"], meaningModifier: "self_realization" },
    aiModifier: { clarity: 0.9 },
  },
  {
    ruleId: "r038",
    priority: 65,
    condition: { cards: [10, 16], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["chaotic_change"], meaningModifier: "unstable_turn" },
    aiModifier: { risk: 0.9 },
  },
  {
    ruleId: "r039",
    priority: 50,
    condition: { cards: [10, 19], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["good_fortune"], meaningModifier: "lucky_break" },
    aiModifier: { opportunity: 0.9 },
  },
  {
    ruleId: "r040",
    priority: 50,
    condition: { cards: [1, 21], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["completion"],
      meaningModifier: "successful_manifestation",
    },
    aiModifier: { opportunity: 0.9 },
  },

  {
    ruleId: "r041",
    priority: 60,
    condition: { cards: [10, 13], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["inevitable_transition"],
      meaningModifier: "fate_driven_change",
    },
    aiModifier: { transformation: 0.85 },
  },
  {
    ruleId: "r042",
    priority: 55,
    condition: { cards: [11, 20], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["karma"], meaningModifier: "justice_realized" },
    aiModifier: { balance: 0.9 },
  },
  {
    ruleId: "r043",
    priority: 60,
    condition: { cards: [11, 15], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["legal_issue"], meaningModifier: "unfair_action" },
    aiModifier: { risk: 0.85 },
  },
  {
    ruleId: "r044",
    priority: 55,
    condition: { cards: [12, 13], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["transition"],
      meaningModifier: "sacrifice_leads_change",
    },
    aiModifier: { transformation: 0.85 },
  },
  {
    ruleId: "r045",
    priority: 50,
    condition: { cards: [12, 9], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["deep_pause"], meaningModifier: "reflective_waiting" },
    aiModifier: { clarity: 0.75 },
  },
  {
    ruleId: "r046",
    priority: 65,
    condition: { cards: [13, 16], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["destruction"], meaningModifier: "sudden_ending" },
    aiModifier: { risk: 0.9 },
  },
  {
    ruleId: "r047",
    priority: 50,
    condition: { cards: [13, 17], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["rebirth"], meaningModifier: "hope_after_end" },
    aiModifier: { hope: 0.9 },
  },
  {
    ruleId: "r048",
    priority: 50,
    condition: { cards: [14, 17], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["peaceful_optimism"], meaningModifier: "stable_hope" },
    aiModifier: { stability: 0.85 },
  },
  {
    ruleId: "r049",
    priority: 70,
    condition: { cards: [15, 16], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["danger"], meaningModifier: "destructive_attachment" },
    aiModifier: { risk: 0.95 },
  },
  {
    ruleId: "r050",
    priority: 55,
    condition: { cards: [17, 19], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["bright_future"], meaningModifier: "hopeful_success" },
    aiModifier: { success: 0.9 },
  },
  {
    ruleId: "r051",
    priority: 50,
    condition: { cards: [0, 22], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["new_adventure"], meaningModifier: "bold_start" },
    aiModifier: { opportunity: 0.75 },
  },
  {
    ruleId: "r052",
    priority: 55,
    condition: { cards: [0, 24], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["impulsive_action"], meaningModifier: "risky_effort" },
    aiModifier: { risk: 0.7 },
  },
  {
    ruleId: "r053",
    priority: 50,
    condition: { cards: [0, 36], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["emotional_beginning"],
      meaningModifier: "innocent_feelings",
    },
    aiModifier: { relationship: 0.75 },
  },
  {
    ruleId: "r054",
    priority: 55,
    condition: { cards: [0, 50], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["conflict"], meaningModifier: "careless_argument" },
    aiModifier: { risk: 0.7 },
  },
  {
    ruleId: "r055",
    priority: 55,
    condition: { cards: [0, 64], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_risk"],
      meaningModifier: "unplanned_spending",
    },
    aiModifier: { risk: 0.75 },
  },

  {
    ruleId: "r056",
    priority: 50,
    condition: { cards: [1, 22], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["initiative"], meaningModifier: "active_creation" },
    aiModifier: { opportunity: 0.85 },
  },
  {
    ruleId: "r057",
    priority: 55,
    condition: { cards: [1, 28], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["planning"], meaningModifier: "strategic_expansion" },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r058",
    priority: 55,
    condition: { cards: [1, 40], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["emotional_message"],
      meaningModifier: "romantic_expression",
    },
    aiModifier: { relationship: 0.8 },
  },
  {
    ruleId: "r059",
    priority: 60,
    condition: { cards: [1, 53], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["intellectual_power"],
      meaningModifier: "sharp_strategy",
    },
    aiModifier: { clarity: 0.9 },
  },
  {
    ruleId: "r060",
    priority: 55,
    condition: { cards: [1, 70], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_skill"],
      meaningModifier: "practical_manifestation",
    },
    aiModifier: { money: 0.85 },
  },

  {
    ruleId: "r061",
    priority: 50,
    condition: { cards: [2, 36], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["deep_feelings"], meaningModifier: "intuitive_love" },
    aiModifier: { relationship: 0.8 },
  },
  {
    ruleId: "r062",
    priority: 55,
    condition: { cards: [2, 50], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["hidden_conflict"],
      meaningModifier: "silent_tension",
    },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r063",
    priority: 50,
    condition: { cards: [2, 66], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_insight"],
      meaningModifier: "careful_resources",
    },
    aiModifier: { money: 0.8 },
  },
  {
    ruleId: "r064",
    priority: 55,
    condition: { cards: [2, 73], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["long_term_security"],
      meaningModifier: "intuitive_planning",
    },
    aiModifier: { stability: 0.85 },
  },

  {
    ruleId: "r065",
    priority: 50,
    condition: { cards: [3, 36], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["romance_growth"],
      meaningModifier: "affection_flourishes",
    },
    aiModifier: { relationship: 0.9 },
  },
  {
    ruleId: "r066",
    priority: 55,
    condition: { cards: [3, 41], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["celebration"], meaningModifier: "joyful_event" },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r067",
    priority: 50,
    condition: { cards: [3, 70], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_growth"],
      meaningModifier: "prosperity_develops",
    },
    aiModifier: { money: 0.9 },
  },
  {
    ruleId: "r068",
    priority: 60,
    condition: { cards: [3, 72], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["luxury"], meaningModifier: "abundant_lifestyle" },
    aiModifier: { money: 0.85 },
  },

  {
    ruleId: "r069",
    priority: 55,
    condition: { cards: [4, 28], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["leadership"],
      meaningModifier: "commanding_direction",
    },
    aiModifier: { dominance: 0.85 },
  },
  {
    ruleId: "r070",
    priority: 55,
    condition: { cards: [4, 53], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["authority"], meaningModifier: "strategic_control" },
    aiModifier: { success: 0.8 },
  },
  {
    ruleId: "r071",
    priority: 60,
    condition: { cards: [4, 69], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_structure"],
      meaningModifier: "stable_management",
    },
    aiModifier: { money: 0.85 },
  },

  {
    ruleId: "r072",
    priority: 50,
    condition: { cards: [5, 41], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["community"], meaningModifier: "shared_values" },
    aiModifier: { relationship: 0.75 },
  },
  {
    ruleId: "r073",
    priority: 55,
    condition: { cards: [5, 53], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["ethical_strategy"],
      meaningModifier: "principled_action",
    },
    aiModifier: { clarity: 0.8 },
  },
  {
    ruleId: "r074",
    priority: 60,
    condition: { cards: [5, 73], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["legacy"], meaningModifier: "tradition_continues" },
    aiModifier: { stability: 0.85 },
  },

  {
    ruleId: "r075",
    priority: 50,
    condition: { cards: [6, 36], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["romantic_offer"],
      meaningModifier: "new_relationship",
    },
    aiModifier: { relationship: 0.9 },
  },
  {
    ruleId: "r076",
    priority: 60,
    condition: { cards: [6, 40], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["love_message"], meaningModifier: "confession" },
    aiModifier: { relationship: 0.9 },
  },
  {
    ruleId: "r077",
    priority: 50,
    condition: { cards: [6, 41], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["romantic_union"], meaningModifier: "commitment" },
    aiModifier: { relationship: 0.95 },
  },

  {
    ruleId: "r078",
    priority: 50,
    condition: { cards: [7, 24], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["fast_action"], meaningModifier: "rapid_progress" },
    aiModifier: { success: 0.8 },
  },
  {
    ruleId: "r079",
    priority: 55,
    condition: { cards: [7, 31], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["competition"],
      meaningModifier: "victory_through_effort",
    },
    aiModifier: { success: 0.8 },
  },
  {
    ruleId: "r080",
    priority: 55,
    condition: { cards: [7, 54], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["strategic_victory"], meaningModifier: "clever_win" },
    aiModifier: { success: 0.85 },
  },

  {
    ruleId: "r081",
    priority: 55,
    condition: { cards: [8, 50], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["mental_control"],
      meaningModifier: "discipline_over_conflict",
    },
    aiModifier: { clarity: 0.85 },
  },
  {
    ruleId: "r082",
    priority: 60,
    condition: { cards: [8, 52], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["anxiety"], meaningModifier: "inner_pressure" },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r083",
    priority: 50,
    condition: { cards: [8, 70], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["persistent_effort"],
      meaningModifier: "steady_growth",
    },
    aiModifier: { success: 0.8 },
  },

  {
    ruleId: "r084",
    priority: 55,
    condition: { cards: [9, 52], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["overthinking"], meaningModifier: "isolated_worry" },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r085",
    priority: 50,
    condition: { cards: [9, 73], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["long_term_view"], meaningModifier: "wise_planning" },
    aiModifier: { stability: 0.85 },
  },

  {
    ruleId: "r086",
    priority: 55,
    condition: { cards: [10, 24], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["sudden_movement"], meaningModifier: "rapid_shift" },
    aiModifier: { change: 0.85 },
  },
  {
    ruleId: "r087",
    priority: 60,
    condition: { cards: [10, 54], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["strategic_luck"],
      meaningModifier: "fortunate_advantage",
    },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r088",
    priority: 55,
    condition: { cards: [10, 70], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["financial_turn"], meaningModifier: "money_cycle" },
    aiModifier: { money: 0.85 },
  },

  {
    ruleId: "r089",
    priority: 55,
    condition: { cards: [11, 53], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["fair_judgment"], meaningModifier: "clear_truth" },
    aiModifier: { clarity: 0.9 },
  },
  {
    ruleId: "r090",
    priority: 60,
    condition: { cards: [11, 63], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["legal_conflict"],
      meaningModifier: "serious_decision",
    },
    aiModifier: { risk: 0.8 },
  },

  {
    ruleId: "r091",
    priority: 55,
    condition: { cards: [12, 52], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["mental_block"], meaningModifier: "sacrifice_needed" },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r092",
    priority: 55,
    condition: { cards: [12, 73], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["long_pause"], meaningModifier: "waiting_period" },
    aiModifier: { stability: 0.7 },
  },

  {
    ruleId: "r093",
    priority: 60,
    condition: { cards: [13, 52], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["mental_break"], meaningModifier: "painful_ending" },
    aiModifier: { risk: 0.85 },
  },
  {
    ruleId: "r094",
    priority: 55,
    condition: { cards: [13, 69], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["financial_end"], meaningModifier: "resource_reset" },
    aiModifier: { money: 0.7 },
  },

  {
    ruleId: "r095",
    priority: 50,
    condition: { cards: [14, 36], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["balanced_love"],
      meaningModifier: "healthy_emotions",
    },
    aiModifier: { relationship: 0.85 },
  },
  {
    ruleId: "r096",
    priority: 55,
    condition: { cards: [14, 41], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["harmonious_event"],
      meaningModifier: "peaceful_celebration",
    },
    aiModifier: { success: 0.85 },
  },

  {
    ruleId: "r097",
    priority: 65,
    condition: { cards: [15, 52], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["mental_trap"], meaningModifier: "obsessive_thought" },
    aiModifier: { risk: 0.9 },
  },
  {
    ruleId: "r098",
    priority: 60,
    condition: { cards: [15, 69], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["material_attachment"], meaningModifier: "greed" },
    aiModifier: { risk: 0.85 },
  },

  {
    ruleId: "r099",
    priority: 65,
    condition: { cards: [16, 52], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["sudden_shock"], meaningModifier: "mental_collapse" },
    aiModifier: { risk: 0.9 },
  },
  {
    ruleId: "r100",
    priority: 60,
    condition: { cards: [16, 31], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["conflict_break"],
      meaningModifier: "chaotic_argument",
    },
    aiModifier: { risk: 0.85 },
  },

  {
    ruleId: "r101",
    priority: 50,
    condition: { cards: [17, 36], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["romantic_hope"],
      meaningModifier: "gentle_affection",
    },
    aiModifier: { relationship: 0.85 },
  },
  {
    ruleId: "r102",
    priority: 55,
    condition: { cards: [17, 41], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["positive_event"],
      meaningModifier: "hopeful_gathering",
    },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r103",
    priority: 55,
    condition: { cards: [17, 73], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["future_security"],
      meaningModifier: "hopeful_investment",
    },
    aiModifier: { money: 0.8 },
  },

  {
    ruleId: "r104",
    priority: 60,
    condition: { cards: [18, 52], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["fear"], meaningModifier: "anxious_confusion" },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r105",
    priority: 60,
    condition: { cards: [18, 50], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["misunderstanding"],
      meaningModifier: "hidden_argument",
    },
    aiModifier: { risk: 0.75 },
  },

  {
    ruleId: "r106",
    priority: 50,
    condition: { cards: [19, 36], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["happy_love"], meaningModifier: "warm_relationship" },
    aiModifier: { relationship: 0.9 },
  },
  {
    ruleId: "r107",
    priority: 55,
    condition: { cards: [19, 41], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["celebration"], meaningModifier: "joyful_success" },
    aiModifier: { success: 0.9 },
  },
  {
    ruleId: "r108",
    priority: 55,
    condition: { cards: [19, 72], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["luxury_success"], meaningModifier: "wealth_display" },
    aiModifier: { money: 0.9 },
  },

  {
    ruleId: "r109",
    priority: 55,
    condition: { cards: [20, 52], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["realization"], meaningModifier: "awakening_truth" },
    aiModifier: { clarity: 0.9 },
  },
  {
    ruleId: "r110",
    priority: 55,
    condition: { cards: [20, 73], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["legacy_call"], meaningModifier: "purpose_continues" },
    aiModifier: { stability: 0.85 },
  },

  {
    ruleId: "r111",
    priority: 50,
    condition: { cards: [21, 28], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["global_expansion"],
      meaningModifier: "successful_growth",
    },
    aiModifier: { success: 0.9 },
  },
  {
    ruleId: "r112",
    priority: 50,
    condition: { cards: [21, 36], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["complete_love"],
      meaningModifier: "fulfilling_relationship",
    },
    aiModifier: { relationship: 0.9 },
  },
  {
    ruleId: "r113",
    priority: 55,
    condition: { cards: [21, 70], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_completion"],
      meaningModifier: "wealth_goal_reached",
    },
    aiModifier: { money: 0.9 },
  },
  {
    ruleId: "r114",
    priority: 55,
    condition: { cards: [21, 41], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["final_celebration"],
      meaningModifier: "major_success",
    },
    aiModifier: { success: 0.95 },
  },
  {
    ruleId: "r115",
    priority: 60,
    condition: { cards: [21, 52], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["ending_truth"], meaningModifier: "truth_revealed" },
    aiModifier: { clarity: 0.85 },
  },
  {
    ruleId: "r116",
    priority: 50,
    condition: { cards: [0, 41], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["celebration_start"],
      meaningModifier: "spontaneous_gathering",
    },
    aiModifier: { relationship: 0.75 },
  },
  {
    ruleId: "r117",
    priority: 55,
    condition: { cards: [0, 52], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["careless_anxiety"],
      meaningModifier: "worry_without_plan",
    },
    aiModifier: { risk: 0.7 },
  },
  {
    ruleId: "r118",
    priority: 55,
    condition: { cards: [1, 24], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["initiative_action"],
      meaningModifier: "rapid_execution",
    },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r119",
    priority: 55,
    condition: { cards: [1, 31], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["strategic_competition"],
      meaningModifier: "winning_through_skill",
    },
    aiModifier: { success: 0.8 },
  },
  {
    ruleId: "r120",
    priority: 50,
    condition: { cards: [2, 41], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["emotional_connection"],
      meaningModifier: "intuitive_bond",
    },
    aiModifier: { relationship: 0.8 },
  },
  {
    ruleId: "r121",
    priority: 60,
    condition: { cards: [2, 52], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["hidden_worry"],
      meaningModifier: "subconscious_fear",
    },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r122",
    priority: 55,
    condition: { cards: [3, 28], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["creative_expansion"],
      meaningModifier: "productive_growth",
    },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r123",
    priority: 55,
    condition: { cards: [3, 73], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["family_prosperity"],
      meaningModifier: "stable_abundance",
    },
    aiModifier: { money: 0.9 },
  },
  {
    ruleId: "r124",
    priority: 60,
    condition: { cards: [4, 52], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["mental_pressure"],
      meaningModifier: "authority_stress",
    },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r125",
    priority: 55,
    condition: { cards: [4, 73], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["legacy_power"],
      meaningModifier: "long_term_control",
    },
    aiModifier: { stability: 0.9 },
  },
  {
    ruleId: "r126",
    priority: 50,
    condition: { cards: [5, 36], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["shared_affection"],
      meaningModifier: "traditional_romance",
    },
    aiModifier: { relationship: 0.85 },
  },
  {
    ruleId: "r127",
    priority: 60,
    condition: { cards: [5, 52], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["moral_anxiety"], meaningModifier: "guilt_pressure" },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r128",
    priority: 55,
    condition: { cards: [6, 28], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["relationship_future"],
      meaningModifier: "planning_together",
    },
    aiModifier: { relationship: 0.9 },
  },
  {
    ruleId: "r129",
    priority: 55,
    condition: { cards: [6, 73], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["family_union"],
      meaningModifier: "lasting_commitment",
    },
    aiModifier: { relationship: 0.95 },
  },
  {
    ruleId: "r130",
    priority: 55,
    condition: { cards: [7, 52], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["stressful_drive"],
      meaningModifier: "pressure_to_win",
    },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r131",
    priority: 50,
    condition: { cards: [7, 70], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_progress"],
      meaningModifier: "career_movement",
    },
    aiModifier: { money: 0.85 },
  },
  {
    ruleId: "r132",
    priority: 55,
    condition: { cards: [8, 31], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["strength_in_conflict"],
      meaningModifier: "calm_competition",
    },
    aiModifier: { success: 0.8 },
  },
  {
    ruleId: "r133",
    priority: 60,
    condition: { cards: [8, 52], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["internal_pressure"],
      meaningModifier: "suppressed_emotion",
    },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r134",
    priority: 50,
    condition: { cards: [9, 41], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["quiet_celebration"],
      meaningModifier: "small_happiness",
    },
    aiModifier: { relationship: 0.75 },
  },
  {
    ruleId: "r135",
    priority: 55,
    condition: { cards: [9, 70], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["careful_work"],
      meaningModifier: "slow_financial_growth",
    },
    aiModifier: { money: 0.8 },
  },
  {
    ruleId: "r136",
    priority: 60,
    condition: { cards: [10, 52], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["unstable_thoughts"],
      meaningModifier: "chaotic_mindset",
    },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r137",
    priority: 55,
    condition: { cards: [10, 41], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["sudden_party"], meaningModifier: "unexpected_event" },
    aiModifier: { success: 0.8 },
  },
  {
    ruleId: "r138",
    priority: 55,
    condition: { cards: [11, 52], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["harsh_truth"], meaningModifier: "painful_judgment" },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r139",
    priority: 50,
    condition: { cards: [11, 70], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_fairness"],
      meaningModifier: "balanced_payment",
    },
    aiModifier: { money: 0.85 },
  },
  {
    ruleId: "r140",
    priority: 60,
    condition: { cards: [12, 50], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["conflict_pause"],
      meaningModifier: "argument_stalemate",
    },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r141",
    priority: 55,
    condition: { cards: [12, 70], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["delayed_income"],
      meaningModifier: "waiting_for_result",
    },
    aiModifier: { money: 0.75 },
  },
  {
    ruleId: "r142",
    priority: 60,
    condition: { cards: [13, 41], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["ending_event"],
      meaningModifier: "farewell_gathering",
    },
    aiModifier: { change: 0.85 },
  },
  {
    ruleId: "r143",
    priority: 60,
    condition: { cards: [13, 50], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["harsh_conflict"],
      meaningModifier: "painful_argument",
    },
    aiModifier: { risk: 0.85 },
  },
  {
    ruleId: "r144",
    priority: 50,
    condition: { cards: [14, 28], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["balanced_growth"],
      meaningModifier: "steady_progress",
    },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r145",
    priority: 55,
    condition: { cards: [14, 70], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_balance"],
      meaningModifier: "controlled_spending",
    },
    aiModifier: { money: 0.85 },
  },
  {
    ruleId: "r146",
    priority: 65,
    condition: { cards: [15, 50], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["toxic_conflict"],
      meaningModifier: "destructive_argument",
    },
    aiModifier: { risk: 0.9 },
  },
  {
    ruleId: "r147",
    priority: 60,
    condition: { cards: [15, 73], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["material_trap"],
      meaningModifier: "greed_family_issue",
    },
    aiModifier: { risk: 0.85 },
  },
  {
    ruleId: "r148",
    priority: 65,
    condition: { cards: [16, 41], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["disrupted_event"],
      meaningModifier: "party_collapse",
    },
    aiModifier: { risk: 0.9 },
  },
  {
    ruleId: "r149",
    priority: 60,
    condition: { cards: [16, 70], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["financial_shock"], meaningModifier: "sudden_loss" },
    aiModifier: { money: 0.7 },
  },
  {
    ruleId: "r150",
    priority: 55,
    condition: { cards: [17, 70], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["hopeful_income"],
      meaningModifier: "promising_finance",
    },
    aiModifier: { money: 0.85 },
  },
  {
    ruleId: "r151",
    priority: 50,
    condition: { cards: [22, 23], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["momentum"], meaningModifier: "rapid_growth" },
    aiModifier: { success: 0.8 },
  },
  {
    ruleId: "r152",
    priority: 55,
    condition: { cards: [22, 28], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["vision"], meaningModifier: "ambitious_plan" },
    aiModifier: { opportunity: 0.85 },
  },
  {
    ruleId: "r153",
    priority: 50,
    condition: { cards: [23, 24], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["expansion"], meaningModifier: "fast_progress" },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r154",
    priority: 55,
    condition: { cards: [24, 31], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["competition"], meaningModifier: "action_conflict" },
    aiModifier: { risk: 0.7 },
  },
  {
    ruleId: "r155",
    priority: 50,
    condition: { cards: [24, 33], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["recognition"], meaningModifier: "visible_success" },
    aiModifier: { success: 0.9 },
  },
  {
    ruleId: "r156",
    priority: 55,
    condition: { cards: [25, 31], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["defense"], meaningModifier: "protecting_position" },
    aiModifier: { tension: 0.7 },
  },
  {
    ruleId: "r157",
    priority: 50,
    condition: { cards: [28, 29], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["planning"], meaningModifier: "strategic_growth" },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r158",
    priority: 55,
    condition: { cards: [30, 31], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["pressure"], meaningModifier: "overwhelming_tasks" },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r159",
    priority: 50,
    condition: { cards: [31, 32], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["persistence"], meaningModifier: "holding_ground" },
    aiModifier: { success: 0.8 },
  },
  {
    ruleId: "r160",
    priority: 50,
    condition: { cards: [32, 33], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["victory"], meaningModifier: "defended_success" },
    aiModifier: { success: 0.85 },
  },

  {
    ruleId: "r161",
    priority: 50,
    condition: { cards: [36, 37], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["emotional_flow"],
      meaningModifier: "feelings_deepen",
    },
    aiModifier: { relationship: 0.85 },
  },
  {
    ruleId: "r162",
    priority: 55,
    condition: { cards: [36, 40], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["romance"], meaningModifier: "affection_offer" },
    aiModifier: { relationship: 0.9 },
  },
  {
    ruleId: "r163",
    priority: 55,
    condition: { cards: [37, 41], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["celebration"], meaningModifier: "happy_gathering" },
    aiModifier: { relationship: 0.85 },
  },
  {
    ruleId: "r164",
    priority: 50,
    condition: { cards: [38, 39], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["nostalgia"], meaningModifier: "past_connection" },
    aiModifier: { relationship: 0.8 },
  },
  {
    ruleId: "r165",
    priority: 55,
    condition: { cards: [39, 40], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["romantic_memory"],
      meaningModifier: "past_love_returns",
    },
    aiModifier: { relationship: 0.85 },
  },
  {
    ruleId: "r166",
    priority: 50,
    condition: { cards: [40, 41], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["engagement"],
      meaningModifier: "relationship_milestone",
    },
    aiModifier: { relationship: 0.9 },
  },
  {
    ruleId: "r167",
    priority: 55,
    condition: { cards: [41, 42], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["community"], meaningModifier: "shared_joy" },
    aiModifier: { relationship: 0.8 },
  },
  {
    ruleId: "r168",
    priority: 50,
    condition: { cards: [42, 43], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["illusion"], meaningModifier: "confused_choices" },
    aiModifier: { risk: 0.7 },
  },
  {
    ruleId: "r169",
    priority: 55,
    condition: { cards: [43, 44], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["withdrawal"],
      meaningModifier: "emotional_detachment",
    },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r170",
    priority: 50,
    condition: { cards: [44, 45], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["emotional_recovery"],
      meaningModifier: "moving_forward",
    },
    aiModifier: { hope: 0.8 },
  },

  {
    ruleId: "r171",
    priority: 50,
    condition: { cards: [50, 51], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["mental_tension"], meaningModifier: "minor_conflict" },
    aiModifier: { risk: 0.7 },
  },
  {
    ruleId: "r172",
    priority: 55,
    condition: { cards: [50, 54], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["strategic_argument"],
      meaningModifier: "verbal_competition",
    },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r173",
    priority: 50,
    condition: { cards: [51, 52], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["stress"], meaningModifier: "mental_pressure" },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r174",
    priority: 55,
    condition: { cards: [52, 53], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["clarity"], meaningModifier: "truth_realization" },
    aiModifier: { clarity: 0.85 },
  },
  {
    ruleId: "r175",
    priority: 60,
    condition: { cards: [52, 63], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["collapse"], meaningModifier: "mental_break" },
    aiModifier: { risk: 0.9 },
  },
  {
    ruleId: "r176",
    priority: 50,
    condition: { cards: [53, 54], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["strategy"],
      meaningModifier: "intellectual_advantage",
    },
    aiModifier: { success: 0.8 },
  },
  {
    ruleId: "r177",
    priority: 50,
    condition: { cards: [54, 55], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["escape"], meaningModifier: "leaving_conflict" },
    aiModifier: { risk: 0.7 },
  },
  {
    ruleId: "r178",
    priority: 55,
    condition: { cards: [55, 56], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["deception"], meaningModifier: "hidden_truth" },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r179",
    priority: 50,
    condition: { cards: [56, 57], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["restriction"], meaningModifier: "mental_block" },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r180",
    priority: 55,
    condition: { cards: [57, 58], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["anxiety"], meaningModifier: "growing_worry" },
    aiModifier: { risk: 0.85 },
  },

  {
    ruleId: "r181",
    priority: 60,
    condition: { cards: [58, 59], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["pain"], meaningModifier: "emotional_break" },
    aiModifier: { risk: 0.9 },
  },
  {
    ruleId: "r182",
    priority: 55,
    condition: { cards: [59, 60], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["recovery"], meaningModifier: "rest_after_conflict" },
    aiModifier: { hope: 0.75 },
  },
  {
    ruleId: "r183",
    priority: 50,
    condition: { cards: [60, 61], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["communication"], meaningModifier: "direct_message" },
    aiModifier: { clarity: 0.8 },
  },
  {
    ruleId: "r184",
    priority: 55,
    condition: { cards: [61, 62], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["investigation"], meaningModifier: "seeking_truth" },
    aiModifier: { clarity: 0.85 },
  },
  {
    ruleId: "r185",
    priority: 50,
    condition: { cards: [62, 63], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["final_argument"], meaningModifier: "sharp_conflict" },
    aiModifier: { risk: 0.85 },
  },

  {
    ruleId: "r186",
    priority: 50,
    condition: { cards: [64, 65], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_balance"],
      meaningModifier: "fair_exchange",
    },
    aiModifier: { money: 0.85 },
  },
  {
    ruleId: "r187",
    priority: 55,
    condition: { cards: [64, 70], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["career_start"], meaningModifier: "new_job" },
    aiModifier: { money: 0.8 },
  },
  {
    ruleId: "r188",
    priority: 50,
    condition: { cards: [65, 66], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["shared_resources"],
      meaningModifier: "mutual_support",
    },
    aiModifier: { money: 0.8 },
  },
  {
    ruleId: "r189",
    priority: 55,
    condition: { cards: [66, 67], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["teamwork"],
      meaningModifier: "productive_collaboration",
    },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r190",
    priority: 50,
    condition: { cards: [67, 68], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["patience"], meaningModifier: "long_term_effort" },
    aiModifier: { success: 0.8 },
  },
  {
    ruleId: "r191",
    priority: 55,
    condition: { cards: [68, 69], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_worry"],
      meaningModifier: "resource_stress",
    },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r192",
    priority: 50,
    condition: { cards: [69, 70], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["career_progress"],
      meaningModifier: "hard_work_reward",
    },
    aiModifier: { money: 0.85 },
  },
  {
    ruleId: "r193",
    priority: 50,
    condition: { cards: [70, 71], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["skill_growth"],
      meaningModifier: "learning_progress",
    },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r194",
    priority: 55,
    condition: { cards: [71, 72], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["wealth"], meaningModifier: "luxury_gain" },
    aiModifier: { money: 0.9 },
  },
  {
    ruleId: "r195",
    priority: 50,
    condition: { cards: [72, 73], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["legacy"], meaningModifier: "family_security" },
    aiModifier: { money: 0.9 },
  },

  {
    ruleId: "r196",
    priority: 55,
    condition: { cards: [64, 69], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["financial_loss"], meaningModifier: "budget_problem" },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r197",
    priority: 50,
    condition: { cards: [65, 70], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["new_income"], meaningModifier: "job_offer" },
    aiModifier: { money: 0.85 },
  },
  {
    ruleId: "r198",
    priority: 55,
    condition: { cards: [66, 71], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["career_growth"], meaningModifier: "promotion_path" },
    aiModifier: { success: 0.9 },
  },
  {
    ruleId: "r199",
    priority: 50,
    condition: { cards: [67, 72], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_reward"],
      meaningModifier: "recognition_bonus",
    },
    aiModifier: { money: 0.9 },
  },
  {
    ruleId: "r200",
    priority: 60,
    condition: { cards: [68, 69], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["poverty_cycle"],
      meaningModifier: "ongoing_financial_struggle",
    },
    aiModifier: { risk: 0.85 },
  },

  {
    ruleId: "r201",
    priority: 50,
    condition: { cards: [36, 42], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["friendship"], meaningModifier: "emotional_support" },
    aiModifier: { relationship: 0.8 },
  },
  {
    ruleId: "r202",
    priority: 55,
    condition: { cards: [37, 43], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["dreamy_love"], meaningModifier: "idealized_romance" },
    aiModifier: { relationship: 0.8 },
  },
  {
    ruleId: "r203",
    priority: 55,
    condition: { cards: [38, 44], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["emotional_shift"],
      meaningModifier: "changing_feelings",
    },
    aiModifier: { risk: 0.7 },
  },
  {
    ruleId: "r204",
    priority: 50,
    condition: { cards: [39, 45], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["moving_on"], meaningModifier: "leaving_past" },
    aiModifier: { hope: 0.8 },
  },
  {
    ruleId: "r205",
    priority: 50,
    condition: { cards: [40, 46], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["creative_feelings"],
      meaningModifier: "romantic_expression",
    },
    aiModifier: { relationship: 0.85 },
  },
  {
    ruleId: "r206",
    priority: 55,
    condition: { cards: [41, 47], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["community_support"],
      meaningModifier: "friendship_strength",
    },
    aiModifier: { relationship: 0.85 },
  },
  {
    ruleId: "r207",
    priority: 50,
    condition: { cards: [42, 48], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["confusion"], meaningModifier: "unclear_emotions" },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r208",
    priority: 55,
    condition: { cards: [43, 49], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["illusion_break"], meaningModifier: "truth_seen" },
    aiModifier: { clarity: 0.8 },
  },
  {
    ruleId: "r209",
    priority: 50,
    condition: { cards: [44, 48], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["apathy"], meaningModifier: "emotional_distance" },
    aiModifier: { risk: 0.7 },
  },
  {
    ruleId: "r210",
    priority: 55,
    condition: { cards: [45, 49], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["healing"], meaningModifier: "hope_after_loss" },
    aiModifier: { hope: 0.85 },
  },

  {
    ruleId: "r211",
    priority: 50,
    condition: { cards: [22, 30], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["burnout"], meaningModifier: "too_many_tasks" },
    aiModifier: { risk: 0.7 },
  },
  {
    ruleId: "r212",
    priority: 55,
    condition: { cards: [23, 31], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["heated_competition"],
      meaningModifier: "strong_rivalry",
    },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r213",
    priority: 50,
    condition: { cards: [24, 32], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["resilience"],
      meaningModifier: "determined_progress",
    },
    aiModifier: { success: 0.8 },
  },
  {
    ruleId: "r214",
    priority: 55,
    condition: { cards: [25, 33], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["leadership"], meaningModifier: "leading_team" },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r215",
    priority: 50,
    condition: { cards: [26, 34], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["bold_move"], meaningModifier: "risk_for_success" },
    aiModifier: { opportunity: 0.85 },
  },
  {
    ruleId: "r216",
    priority: 55,
    condition: { cards: [27, 35], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["visionary_action"],
      meaningModifier: "inspired_leadership",
    },
    aiModifier: { success: 0.9 },
  },
  {
    ruleId: "r217",
    priority: 50,
    condition: { cards: [28, 30], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["overcommitment"],
      meaningModifier: "too_many_projects",
    },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r218",
    priority: 55,
    condition: { cards: [29, 31], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["work_conflict"],
      meaningModifier: "competitive_environment",
    },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r219",
    priority: 50,
    condition: { cards: [30, 33], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["hard_won_success"],
      meaningModifier: "victory_after_struggle",
    },
    aiModifier: { success: 0.9 },
  },
  {
    ruleId: "r220",
    priority: 55,
    condition: { cards: [31, 35], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["chaotic_energy"],
      meaningModifier: "unstable_progress",
    },
    aiModifier: { risk: 0.8 },
  },

  {
    ruleId: "r221",
    priority: 50,
    condition: { cards: [50, 58], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["growing_conflict"],
      meaningModifier: "argument_intensifies",
    },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r222",
    priority: 55,
    condition: { cards: [51, 59], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["mental_exhaustion"],
      meaningModifier: "too_many_arguments",
    },
    aiModifier: { risk: 0.85 },
  },
  {
    ruleId: "r223",
    priority: 50,
    condition: { cards: [52, 60], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["temporary_relief"], meaningModifier: "rest_needed" },
    aiModifier: { hope: 0.7 },
  },
  {
    ruleId: "r224",
    priority: 55,
    condition: { cards: [53, 61], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["direct_truth"], meaningModifier: "clear_statement" },
    aiModifier: { clarity: 0.9 },
  },
  {
    ruleId: "r225",
    priority: 50,
    condition: { cards: [54, 62], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["investigation"],
      meaningModifier: "digging_information",
    },
    aiModifier: { clarity: 0.85 },
  },
  {
    ruleId: "r226",
    priority: 55,
    condition: { cards: [55, 63], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["dangerous_secret"],
      meaningModifier: "truth_exposed",
    },
    aiModifier: { risk: 0.9 },
  },
  {
    ruleId: "r227",
    priority: 50,
    condition: { cards: [56, 60], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["restricted_thought"],
      meaningModifier: "mental_barrier",
    },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r228",
    priority: 55,
    condition: { cards: [57, 61], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["anxious_message"], meaningModifier: "worrying_news" },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r229",
    priority: 50,
    condition: { cards: [58, 62], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["painful_truth"],
      meaningModifier: "sharp_realization",
    },
    aiModifier: { risk: 0.85 },
  },
  {
    ruleId: "r230",
    priority: 55,
    condition: { cards: [59, 63], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["recovery_truth"],
      meaningModifier: "healing_realization",
    },
    aiModifier: { hope: 0.8 },
  },

  {
    ruleId: "r231",
    priority: 50,
    condition: { cards: [64, 68], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_balance"],
      meaningModifier: "careful_budget",
    },
    aiModifier: { money: 0.85 },
  },
  {
    ruleId: "r232",
    priority: 55,
    condition: { cards: [65, 69], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["shared_loss"],
      meaningModifier: "financial_support_needed",
    },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r233",
    priority: 50,
    condition: { cards: [66, 70], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["team_success"], meaningModifier: "work_project" },
    aiModifier: { success: 0.9 },
  },
  {
    ruleId: "r234",
    priority: 55,
    condition: { cards: [67, 71], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["steady_growth"],
      meaningModifier: "consistent_progress",
    },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r235",
    priority: 50,
    condition: { cards: [68, 72], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_improvement"],
      meaningModifier: "slow_recovery",
    },
    aiModifier: { money: 0.8 },
  },
  {
    ruleId: "r236",
    priority: 55,
    condition: { cards: [69, 73], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["family_finance"],
      meaningModifier: "shared_responsibility",
    },
    aiModifier: { money: 0.8 },
  },
  {
    ruleId: "r237",
    priority: 50,
    condition: { cards: [70, 72], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["promotion"], meaningModifier: "career_reward" },
    aiModifier: { money: 0.9 },
  },
  {
    ruleId: "r238",
    priority: 55,
    condition: { cards: [71, 73], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["wealth_security"],
      meaningModifier: "stable_finances",
    },
    aiModifier: { money: 0.9 },
  },
  {
    ruleId: "r239",
    priority: 50,
    condition: { cards: [64, 73], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["inheritance"], meaningModifier: "family_support" },
    aiModifier: { money: 0.85 },
  },
  {
    ruleId: "r240",
    priority: 55,
    condition: { cards: [65, 72], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["generous_help"],
      meaningModifier: "financial_assistance",
    },
    aiModifier: { money: 0.85 },
  },

  {
    ruleId: "r241",
    priority: 50,
    condition: { cards: [22, 36], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["passionate_love"], meaningModifier: "fast_romance" },
    aiModifier: { relationship: 0.85 },
  },
  {
    ruleId: "r242",
    priority: 55,
    condition: { cards: [24, 40], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["romantic_message"],
      meaningModifier: "exciting_confession",
    },
    aiModifier: { relationship: 0.9 },
  },
  {
    ruleId: "r243",
    priority: 50,
    condition: { cards: [28, 41], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["future_relationship"],
      meaningModifier: "long_term_plans",
    },
    aiModifier: { relationship: 0.9 },
  },
  {
    ruleId: "r244",
    priority: 55,
    condition: { cards: [31, 45], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["relationship_conflict"],
      meaningModifier: "argument_then_growth",
    },
    aiModifier: { risk: 0.75 },
  },
  {
    ruleId: "r245",
    priority: 50,
    condition: { cards: [36, 64], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["emotional_support"],
      meaningModifier: "helpful_partner",
    },
    aiModifier: { relationship: 0.85 },
  },
  {
    ruleId: "r246",
    priority: 55,
    condition: { cards: [41, 70], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["career_party"],
      meaningModifier: "work_success_event",
    },
    aiModifier: { success: 0.85 },
  },
  {
    ruleId: "r247",
    priority: 50,
    condition: { cards: [52, 69], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["financial_anxiety"], meaningModifier: "money_worry" },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r248",
    priority: 55,
    condition: { cards: [58, 73], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["painful_family_issue"],
      meaningModifier: "conflict_in_home",
    },
    aiModifier: { risk: 0.85 },
  },
  {
    ruleId: "r249",
    priority: 50,
    condition: { cards: [33, 72], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["public_success"],
      meaningModifier: "recognized_achievement",
    },
    aiModifier: { success: 0.9 },
  },
  {
    ruleId: "r250",
    priority: 55,
    condition: { cards: [30, 69], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["financial_burden"],
      meaningModifier: "heavy_responsibility",
    },
    aiModifier: { risk: 0.8 },
  },
  {
    ruleId: "r251",
    priority: 80,
    condition: { cards: [0, 21], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["cosmic_cycle", "completion"],
      meaningModifier: "destined_completion",
    },
    aiModifier: { opportunity: 0.95 },
  },
  {
    ruleId: "r252",
    priority: 78,
    condition: { cards: [1, 10], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["manifestation", "fate_shift"],
      meaningModifier: "controlled_turning_point",
    },
    aiModifier: { opportunity: 0.88 },
  },
  {
    ruleId: "r253",
    priority: 77,
    condition: { cards: [2, 18], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["intuition", "hidden_truth"],
      meaningModifier: "deep_psychic_revelation",
    },
    aiModifier: { opportunity: 0.86 },
  },
  {
    ruleId: "r254",
    priority: 76,
    condition: { cards: [3, 19], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["creation", "joy"],
      meaningModifier: "abundant_success",
    },
    aiModifier: { opportunity: 0.9 },
  },
  {
    ruleId: "r255",
    priority: 79,
    condition: { cards: [4, 16], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["authority", "collapse"],
      meaningModifier: "power_structure_break",
    },
    aiModifier: { risk: 0.82 },
  },
  {
    ruleId: "r256",
    priority: 75,
    condition: { cards: [5, 20], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["judgement", "spiritual_call"],
      meaningModifier: "awakening_through_tradition",
    },
    aiModifier: { spiritual: 0.9 },
  },
  {
    ruleId: "r257",
    priority: 74,
    condition: { cards: [6, 14], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["harmony", "balance"],
      meaningModifier: "soul_alignment",
    },
    aiModifier: { relationship: 0.92 },
  },
  {
    ruleId: "r258",
    priority: 73,
    condition: { cards: [7, 11], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["discipline", "justice"],
      meaningModifier: "earned_victory",
    },
    aiModifier: { success: 0.87 },
  },
  {
    ruleId: "r259",
    priority: 72,
    condition: { cards: [8, 13], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["strength", "transformation"],
      meaningModifier: "rebirth_through_courage",
    },
    aiModifier: { growth: 0.9 },
  },
  {
    ruleId: "r260",
    priority: 71,
    condition: { cards: [9, 17], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["hope", "guidance"],
      meaningModifier: "inner_light_found",
    },
    aiModifier: { spiritual: 0.88 },
  },
  {
    ruleId: "r261",
    priority: 74,
    condition: { cards: [10, 15], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["fate", "temptation"],
      meaningModifier: "dangerous_opportunity",
    },
    aiModifier: { risk: 0.84 },
  },
  {
    ruleId: "r262",
    priority: 73,
    condition: { cards: [11, 20], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["justice", "rebirth"],
      meaningModifier: "karma_resolution",
    },
    aiModifier: { karma: 0.93 },
  },
  {
    ruleId: "r263",
    priority: 72,
    condition: { cards: [12, 18], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["sacrifice", "illusion"],
      meaningModifier: "confusing_pause",
    },
    aiModifier: { uncertainty: 0.8 },
  },
  {
    ruleId: "r264",
    priority: 71,
    condition: { cards: [13, 19], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["death", "renewal"],
      meaningModifier: "radiant_rebirth",
    },
    aiModifier: { transformation: 0.94 },
  },
  {
    ruleId: "r265",
    priority: 70,
    condition: { cards: [14, 21], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["balance", "completion"],
      meaningModifier: "perfect_harmony",
    },
    aiModifier: { stability: 0.9 },
  },
  {
    ruleId: "r266",
    priority: 69,
    condition: { cards: [15, 16], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["chaos", "liberation"],
      meaningModifier: "toxic_structure_break",
    },
    aiModifier: { risk: 0.9 },
  },
  {
    ruleId: "r267",
    priority: 68,
    condition: { cards: [16, 17], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["collapse", "hope"],
      meaningModifier: "hope_after_crisis",
    },
    aiModifier: { recovery: 0.88 },
  },
  {
    ruleId: "r268",
    priority: 67,
    condition: { cards: [17, 21], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["dream", "fulfillment"],
      meaningModifier: "destiny_realized",
    },
    aiModifier: { opportunity: 0.93 },
  },
  {
    ruleId: "r269",
    priority: 66,
    condition: { cards: [18, 20], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["illusion", "awakening"],
      meaningModifier: "truth_emerges",
    },
    aiModifier: { clarity: 0.87 },
  },
  {
    ruleId: "r270",
    priority: 65,
    condition: { cards: [19, 21], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["success", "completion"],
      meaningModifier: "ultimate_success",
    },
    aiModifier: { success: 0.96 },
  },
  {
    ruleId: "r271",
    priority: 64,
    condition: { cards: [0, 13], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["cycle", "rebirth"],
      meaningModifier: "new_life_path",
    },
    aiModifier: { transformation: 0.91 },
  },
  {
    ruleId: "r272",
    priority: 63,
    condition: { cards: [1, 17], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["vision", "manifestation"],
      meaningModifier: "dream_manifestation",
    },
    aiModifier: { opportunity: 0.9 },
  },
  {
    ruleId: "r273",
    priority: 62,
    condition: { cards: [2, 9], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["wisdom", "introspection"],
      meaningModifier: "inner_truth",
    },
    aiModifier: { spiritual: 0.86 },
  },
  {
    ruleId: "r274",
    priority: 61,
    condition: { cards: [3, 14], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["nurture", "balance"],
      meaningModifier: "harmonious_growth",
    },
    aiModifier: { stability: 0.88 },
  },
  {
    ruleId: "r275",
    priority: 60,
    condition: { cards: [4, 11], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["law", "authority"],
      meaningModifier: "structured_power",
    },
    aiModifier: { control: 0.85 },
  },
  {
    ruleId: "r276",
    priority: 59,
    condition: { cards: [5, 9], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["wisdom", "tradition"],
      meaningModifier: "mentor_guidance",
    },
    aiModifier: { guidance: 0.87 },
  },
  {
    ruleId: "r277",
    priority: 58,
    condition: { cards: [6, 19], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["love", "joy"], meaningModifier: "blessed_union" },
    aiModifier: { relationship: 0.94 },
  },
  {
    ruleId: "r278",
    priority: 57,
    condition: { cards: [7, 16], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["victory", "disruption"],
      meaningModifier: "sudden_turnaround",
    },
    aiModifier: { risk: 0.82 },
  },
  {
    ruleId: "r279",
    priority: 56,
    condition: { cards: [8, 20], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["strength", "awakening"],
      meaningModifier: "powerful_calling",
    },
    aiModifier: { growth: 0.9 },
  },
  {
    ruleId: "r280",
    priority: 55,
    condition: { cards: [9, 21], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["completion", "wisdom"],
      meaningModifier: "sage_completion",
    },
    aiModifier: { clarity: 0.92 },
  },
  {
    ruleId: "r281",
    priority: 54,
    condition: { cards: [10, 18], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["fate", "illusion"],
      meaningModifier: "uncertain_destiny",
    },
    aiModifier: { uncertainty: 0.83 },
  },
  {
    ruleId: "r282",
    priority: 53,
    condition: { cards: [11, 17], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["justice", "hope"], meaningModifier: "fair_outcome" },
    aiModifier: { balance: 0.9 },
  },
  {
    ruleId: "r283",
    priority: 52,
    condition: { cards: [12, 21], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["sacrifice", "completion"],
      meaningModifier: "sacrifice_rewarded",
    },
    aiModifier: { spiritual: 0.88 },
  },
  {
    ruleId: "r284",
    priority: 51,
    condition: { cards: [13, 17], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["rebirth", "hope"],
      meaningModifier: "healing_transformation",
    },
    aiModifier: { recovery: 0.92 },
  },
  {
    ruleId: "r285",
    priority: 50,
    condition: { cards: [14, 19], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["balance", "joy"],
      meaningModifier: "happy_equilibrium",
    },
    aiModifier: { harmony: 0.9 },
  },
  {
    ruleId: "r286",
    priority: 49,
    condition: { cards: [15, 18], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["temptation", "illusion"],
      meaningModifier: "dangerous_deception",
    },
    aiModifier: { risk: 0.91 },
  },
  {
    ruleId: "r287",
    priority: 48,
    condition: { cards: [16, 20], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["shock", "awakening"],
      meaningModifier: "sudden_realization",
    },
    aiModifier: { clarity: 0.89 },
  },
  {
    ruleId: "r288",
    priority: 47,
    condition: { cards: [17, 19], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["hope", "success"], meaningModifier: "dream_success" },
    aiModifier: { success: 0.93 },
  },
  {
    ruleId: "r289",
    priority: 46,
    condition: { cards: [18, 21], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["mystery", "completion"],
      meaningModifier: "hidden_destiny",
    },
    aiModifier: { spiritual: 0.87 },
  },
  {
    ruleId: "r290",
    priority: 45,
    condition: { cards: [0, 10], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["cycle", "chance"],
      meaningModifier: "unexpected_beginning",
    },
    aiModifier: { opportunity: 0.9 },
  },
  {
    ruleId: "r291",
    priority: 44,
    condition: { cards: [1, 20], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["manifestation", "judgement"],
      meaningModifier: "calling_realized",
    },
    aiModifier: { success: 0.9 },
  },
  {
    ruleId: "r292",
    priority: 43,
    condition: { cards: [2, 17], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["intuition", "hope"],
      meaningModifier: "psychic_guidance",
    },
    aiModifier: { spiritual: 0.91 },
  },
  {
    ruleId: "r293",
    priority: 42,
    condition: { cards: [3, 21], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["creation", "completion"],
      meaningModifier: "creative_mastery",
    },
    aiModifier: { success: 0.92 },
  },
  {
    ruleId: "r294",
    priority: 41,
    condition: { cards: [4, 20], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["authority", "awakening"],
      meaningModifier: "leader_called",
    },
    aiModifier: { power: 0.88 },
  },
  {
    ruleId: "r295",
    priority: 40,
    condition: { cards: [5, 17], order: "any", reversedAllowed: true },
    effect: { themeAdd: ["faith", "hope"], meaningModifier: "divine_guidance" },
    aiModifier: { spiritual: 0.94 },
  },
  {
    ruleId: "r296",
    priority: 39,
    condition: { cards: [6, 21], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["union", "completion"],
      meaningModifier: "fated_partnership",
    },
    aiModifier: { relationship: 0.95 },
  },
  {
    ruleId: "r297",
    priority: 38,
    condition: { cards: [7, 19], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["victory", "joy"],
      meaningModifier: "triumphant_success",
    },
    aiModifier: { success: 0.94 },
  },
  {
    ruleId: "r298",
    priority: 37,
    condition: { cards: [8, 21], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["strength", "completion"],
      meaningModifier: "ultimate_endurance",
    },
    aiModifier: { power: 0.9 },
  },
  {
    ruleId: "r299",
    priority: 36,
    condition: { cards: [9, 20], order: "any", reversedAllowed: true },
    effect: {
      themeAdd: ["wisdom", "awakening"],
      meaningModifier: "enlightened_call",
    },
    aiModifier: { clarity: 0.91 },
  },
  {
    ruleId: "r300",
    priority: 85,
    condition: { cards: [0, 21], order: "any", reversedAllowed: false },
    effect: {
      themeAdd: ["alpha_omega", "cosmic_completion"],
      meaningModifier: "absolute_destiny",
    },
    aiModifier: { destiny: 0.99 },
  },
];
