/**
 * 카드별 감정 벡터(VAD)와 전역 카드 ID 매핑을 정의합니다.
 */
export const EMOTION_VECTOR = [
  // 메이저 아르카나
  { id: 0, card: "Fool", valence: 0.6, arousal: 0.65, dominance: 0.4 },
  { id: 1, card: "Magician", valence: 0.75, arousal: 0.7, dominance: 0.85 },
  { id: 2, card: "High Priestess", valence: 0.48, arousal: 0.2, dominance: 0.6 },
  { id: 3, card: "Empress", valence: 0.8, arousal: 0.5, dominance: 0.7 },
  { id: 4, card: "Emperor", valence: 0.65, arousal: 0.6, dominance: 0.95 },
  { id: 5, card: "Hierophant", valence: 0.5, arousal: 0.3, dominance: 0.8 },
  { id: 6, card: "Lovers", valence: 0.85, arousal: 0.7, dominance: 0.65 },
  { id: 7, card: "Chariot", valence: 0.7, arousal: 0.85, dominance: 0.9 },
  { id: 8, card: "Strength", valence: 0.6, arousal: 0.5, dominance: 0.85 },
  { id: 9, card: "Hermit", valence: 0.38, arousal: 0.1, dominance: 0.55 },
  {
    id: 10,
    card: "Wheel of Fortune",
    valence: 0.4,
    arousal: 0.8,
    dominance: 0.3,
  },
  { id: 11, card: "Justice", valence: 0.5, arousal: 0.4, dominance: 0.9 },
  { id: 12, card: "Hanged Man", valence: -0.1, arousal: 0.2, dominance: 0.2 },
  { id: 13, card: "Death", valence: -0.4, arousal: 0.75, dominance: 0.5 },
  { id: 14, card: "Temperance", valence: 0.55, arousal: 0.25, dominance: 0.6 },
  { id: 15, card: "Devil", valence: -0.65, arousal: 0.85, dominance: 0.7 },
  { id: 16, card: "Tower", valence: -0.9, arousal: 1.0, dominance: 0.1 },
  { id: 17, card: "Star", valence: 0.9, arousal: 0.3, dominance: 0.4 },
  { id: 18, card: "Moon", valence: -0.3, arousal: 0.7, dominance: 0.2 },
  { id: 19, card: "Sun", valence: 0.95, arousal: 0.8, dominance: 0.7 },
  { id: 20, card: "Judgement", valence: 0.5, arousal: 0.7, dominance: 0.75 },
  { id: 21, card: "World", valence: 0.85, arousal: 0.55, dominance: 0.9 },
  // 마이너 아르카나
  // 완드
  { id: 0, card: "Ace of Wands", valence: 0.8, arousal: 0.9, dominance: 0.7 },
  { id: 1, card: "Two of Wands", valence: 0.6, arousal: 0.6, dominance: 0.65 },
  {
    id: 2,
    card: "Three of Wands",
    valence: 0.75,
    arousal: 0.7,
    dominance: 0.7,
  },
  { id: 3, card: "Four of Wands", valence: 0.9, arousal: 0.6, dominance: 0.65 },
  { id: 4, card: "Five of Wands", valence: -0.2, arousal: 0.8, dominance: 0.5 },
  { id: 5, card: "Six of Wands", valence: 0.85, arousal: 0.75, dominance: 0.8 },
  {
    id: 6,
    card: "Seven of Wands",
    valence: 0.1,
    arousal: 0.8,
    dominance: 0.75,
  },
  {
    id: 7,
    card: "Eight of Wands",
    valence: 0.7,
    arousal: 0.95,
    dominance: 0.6,
  },
  {
    id: 8,
    card: "Nine of Wands",
    valence: -0.1,
    arousal: 0.6,
    dominance: 0.65,
  },
  { id: 9, card: "Ten of Wands", valence: -0.6, arousal: 0.7, dominance: 0.2 },
  {
    id: 10,
    card: "Page of Wands",
    valence: 0.75,
    arousal: 0.85,
    dominance: 0.4,
  },
  {
    id: 11,
    card: "Knight of Wands",
    valence: 0.65,
    arousal: 0.95,
    dominance: 0.8,
  },
  {
    id: 12,
    card: "Queen of Wands",
    valence: 0.8,
    arousal: 0.7,
    dominance: 0.85,
  },
  {
    id: 13,
    card: "King of Wands",
    valence: 0.75,
    arousal: 0.75,
    dominance: 0.95,
  },

  // 컵
  { id: 14, card: "Ace of Cups", valence: 0.9, arousal: 0.6, dominance: 0.5 },
  { id: 15, card: "Two of Cups", valence: 0.95, arousal: 0.65, dominance: 0.6 },
  {
    id: 16,
    card: "Three of Cups",
    valence: 0.9,
    arousal: 0.75,
    dominance: 0.55,
  },
  { id: 17, card: "Four of Cups", valence: -0.1, arousal: 0.2, dominance: 0.3 },
  {
    id: 18,
    card: "Five of Cups",
    valence: -0.75,
    arousal: 0.5,
    dominance: 0.2,
  },
  { id: 19, card: "Six of Cups", valence: 0.7, arousal: 0.4, dominance: 0.45 },
  {
    id: 20,
    card: "Seven of Cups",
    valence: 0.1,
    arousal: 0.7,
    dominance: 0.25,
  },
  {
    id: 21,
    card: "Eight of Cups",
    valence: -0.4,
    arousal: 0.5,
    dominance: 0.4,
  },
  { id: 22, card: "Nine of Cups", valence: 0.9, arousal: 0.6, dominance: 0.65 },
  { id: 23, card: "Ten of Cups", valence: 0.95, arousal: 0.65, dominance: 0.7 },
  {
    id: 24,
    card: "Page of Cups",
    valence: 0.75,
    arousal: 0.55,
    dominance: 0.35,
  },
  {
    id: 25,
    card: "Knight of Cups",
    valence: 0.7,
    arousal: 0.65,
    dominance: 0.5,
  },
  {
    id: 26,
    card: "Queen of Cups",
    valence: 0.8,
    arousal: 0.4,
    dominance: 0.65,
  },
  {
    id: 27,
    card: "King of Cups",
    valence: 0.75,
    arousal: 0.45,
    dominance: 0.85,
  },

  // 소드
  {
    id: 28,
    card: "Ace of Swords",
    valence: 0.4,
    arousal: 0.85,
    dominance: 0.8,
  },
  {
    id: 29,
    card: "Two of Swords",
    valence: -0.2,
    arousal: 0.3,
    dominance: 0.4,
  },
  {
    id: 30,
    card: "Three of Swords",
    valence: -0.9,
    arousal: 0.7,
    dominance: 0.1,
  },
  {
    id: 31,
    card: "Four of Swords",
    valence: 0.1,
    arousal: 0.1,
    dominance: 0.4,
  },
  {
    id: 32,
    card: "Five of Swords",
    valence: -0.7,
    arousal: 0.7,
    dominance: 0.6,
  },
  { id: 33, card: "Six of Swords", valence: 0.2, arousal: 0.3, dominance: 0.4 },
  {
    id: 34,
    card: "Seven of Swords",
    valence: -0.4,
    arousal: 0.6,
    dominance: 0.65,
  },
  {
    id: 35,
    card: "Eight of Swords",
    valence: -0.75,
    arousal: 0.5,
    dominance: 0.1,
  },
  {
    id: 36,
    card: "Nine of Swords",
    valence: -0.95,
    arousal: 0.8,
    dominance: 0.05,
  },
  {
    id: 37,
    card: "Ten of Swords",
    valence: -1.0,
    arousal: 0.9,
    dominance: 0.0,
  },
  {
    id: 38,
    card: "Page of Swords",
    valence: 0.2,
    arousal: 0.7,
    dominance: 0.5,
  },
  {
    id: 39,
    card: "Knight of Swords",
    valence: 0.1,
    arousal: 0.95,
    dominance: 0.8,
  },
  {
    id: 40,
    card: "Queen of Swords",
    valence: 0.15,
    arousal: 0.5,
    dominance: 0.85,
  },
  {
    id: 41,
    card: "King of Swords",
    valence: 0.2,
    arousal: 0.55,
    dominance: 0.95,
  },
  // 펜타클
  {
    id: 42,
    card: "Ace of Pentacles",
    valence: 0.85,
    arousal: 0.6,
    dominance: 0.65,
  },
  {
    id: 43,
    card: "Two of Pentacles",
    valence: 0.5,
    arousal: 0.6,
    dominance: 0.5,
  },
  {
    id: 44,
    card: "Three of Pentacles",
    valence: 0.75,
    arousal: 0.55,
    dominance: 0.7,
  },
  {
    id: 45,
    card: "Four of Pentacles",
    valence: 0.0,
    arousal: 0.3,
    dominance: 0.6,
  },
  {
    id: 46,
    card: "Five of Pentacles",
    valence: -0.85,
    arousal: 0.5,
    dominance: 0.1,
  },
  {
    id: 47,
    card: "Six of Pentacles",
    valence: 0.7,
    arousal: 0.45,
    dominance: 0.65,
  },
  {
    id: 48,
    card: "Seven of Pentacles",
    valence: 0.3,
    arousal: 0.3,
    dominance: 0.5,
  },
  {
    id: 49,
    card: "Eight of Pentacles",
    valence: 0.7,
    arousal: 0.65,
    dominance: 0.75,
  },
  {
    id: 50,
    card: "Nine of Pentacles",
    valence: 0.9,
    arousal: 0.4,
    dominance: 0.8,
  },
  {
    id: 51,
    card: "Ten of Pentacles",
    valence: 0.95,
    arousal: 0.5,
    dominance: 0.9,
  },
  {
    id: 52,
    card: "Page of Pentacles",
    valence: 0.65,
    arousal: 0.5,
    dominance: 0.45,
  },
  {
    id: 53,
    card: "Knight of Pentacles",
    valence: 0.55,
    arousal: 0.35,
    dominance: 0.8,
  },
  {
    id: 54,
    card: "Queen of Pentacles",
    valence: 0.8,
    arousal: 0.4,
    dominance: 0.85,
  },
  {
    id: 55,
    card: "King of Pentacles",
    valence: 0.85,
    arousal: 0.45,
    dominance: 0.95,
  },
];

const MAJOR_ARCANA_COUNT = 22;

const toGlobalCardId = (legacyId: number, index: number): number => {
  // 메이저 아르카나는 전역 ID(0~21)를 그대로 사용합니다.
  if (index < MAJOR_ARCANA_COUNT) return legacyId;
  // 마이너 아르카나의 레거시 ID(0~55)를 전역 ID(22~77)로 변환합니다.
  return legacyId + MAJOR_ARCANA_COUNT;
};

export const EMOTION_VECTOR_BY_CARD_ID = EMOTION_VECTOR.map((entry, index) => ({
  ...entry,
  cardId: toGlobalCardId(entry.id, index),
  legacyId: entry.id,
}));



