/**
 * 카드별 의미 태그 코퍼스와 정규화 export를 정의합니다.
 */
export const SEMENTIG_TAG = [
  // 메이저 아르카나
  {
    cardId: 0,
    name: "The Fool",
    themes: ["beginning", "freedom", "risk", "journey", "innocence"],
    emotions: ["optimism", "curiosity", "excitement"],
    lifeAreas: {
      love: 0.4,
      career: 0.6,
      finance: 0.3,
      health: 0.4,
      spiritual: 0.7,
      personal: 0.8,
      advice: 0.7,
    },
    polarity: 0.6,
  },
  {
    cardId: 1,
    name: "The Magician",
    themes: ["manifestation", "skill", "willpower", "creation", "action"],
    emotions: ["confidence", "focus"],
    lifeAreas: {
      love: 0.5,
      career: 0.8,
      finance: 0.7,
      health: 0.5,
      spiritual: 0.6,
      personal: 0.7,
      advice: 0.8,
    },
    polarity: 0.7,
  },
  {
    cardId: 2,
    name: "The High Priestess",
    themes: [
      "intuition",
      "mystery",
      "subconscious",
      "inner_knowledge",
      "silence",
    ],
    emotions: ["calm", "intuition", "reserve"],
    lifeAreas: {
      love: 0.5,
      career: 0.4,
      finance: 0.3,
      health: 0.5,
      spiritual: 0.9,
      personal: 0.8,
      advice: 0.8,
    },
    polarity: 0.5,
  },
  {
    cardId: 3,
    name: "The Empress",
    themes: ["nurturing", "abundance", "fertility", "growth", "comfort"],
    emotions: ["warmth", "love", "security"],
    lifeAreas: {
      love: 0.8,
      career: 0.5,
      finance: 0.6,
      health: 0.7,
      spiritual: 0.6,
      personal: 0.7,
      advice: 0.6,
    },
    polarity: 0.8,
  },
  {
    cardId: 4,
    name: "The Emperor",
    themes: ["authority", "structure", "control", "stability", "leadership"],
    emotions: ["confidence", "determination"],
    lifeAreas: {
      love: 0.5,
      career: 0.9,
      finance: 0.8,
      health: 0.5,
      spiritual: 0.4,
      personal: 0.6,
      advice: 0.7,
    },
    polarity: 0.6,
  },
  {
    cardId: 5,
    name: "The Hierophant",
    themes: ["tradition", "institution", "belief", "guidance", "learning"],
    emotions: ["faith", "respect"],
    lifeAreas: {
      love: 0.6,
      career: 0.6,
      finance: 0.5,
      health: 0.4,
      spiritual: 0.8,
      personal: 0.6,
      advice: 0.9,
    },
    polarity: 0.5,
  },
  {
    cardId: 6,
    name: "The Lovers",
    themes: ["union", "choice", "relationship", "alignment", "values"],
    emotions: ["love", "passion", "connection"],
    lifeAreas: {
      love: 0.95,
      career: 0.5,
      finance: 0.4,
      health: 0.5,
      spiritual: 0.6,
      personal: 0.7,
      advice: 0.7,
    },
    polarity: 0.8,
  },
  {
    cardId: 7,
    name: "The Chariot",
    themes: ["victory", "determination", "control", "direction", "momentum"],
    emotions: ["drive", "confidence"],
    lifeAreas: {
      love: 0.4,
      career: 0.8,
      finance: 0.6,
      health: 0.6,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.8,
    },
    polarity: 0.7,
  },
  {
    cardId: 8,
    name: "Strength",
    themes: ["courage", "patience", "inner_strength", "compassion", "control"],
    emotions: ["calm", "confidence", "compassion"],
    lifeAreas: {
      love: 0.6,
      career: 0.6,
      finance: 0.5,
      health: 0.7,
      spiritual: 0.6,
      personal: 0.8,
      advice: 0.7,
    },
    polarity: 0.7,
  },
  {
    cardId: 9,
    name: "The Hermit",
    themes: ["introspection", "solitude", "wisdom", "search", "reflection"],
    emotions: ["calm", "distance", "contemplation"],
    lifeAreas: {
      love: 0.3,
      career: 0.4,
      finance: 0.3,
      health: 0.5,
      spiritual: 0.9,
      personal: 0.9,
      advice: 0.8,
    },
    polarity: 0.4,
  },
  {
    cardId: 10,
    name: "Wheel of Fortune",
    themes: ["cycle", "change", "fate", "turning_point", "luck"],
    emotions: ["anticipation", "uncertainty"],
    lifeAreas: {
      love: 0.5,
      career: 0.6,
      finance: 0.6,
      health: 0.5,
      spiritual: 0.6,
      personal: 0.6,
      advice: 0.6,
    },
    polarity: 0.5,
  },
  {
    cardId: 11,
    name: "Justice",
    themes: ["balance", "truth", "law", "accountability", "fairness"],
    emotions: ["clarity", "seriousness"],
    lifeAreas: {
      love: 0.5,
      career: 0.7,
      finance: 0.7,
      health: 0.5,
      spiritual: 0.5,
      personal: 0.6,
      advice: 0.8,
    },
    polarity: 0.6,
  },
  {
    cardId: 12,
    name: "The Hanged Man",
    themes: ["suspension", "sacrifice", "new_perspective", "letting_go"],
    emotions: ["acceptance", "patience"],
    lifeAreas: {
      love: 0.4,
      career: 0.4,
      finance: 0.3,
      health: 0.5,
      spiritual: 0.8,
      personal: 0.8,
      advice: 0.9,
    },
    polarity: 0.3,
  },
  {
    cardId: 13,
    name: "Death",
    themes: ["ending", "transformation", "rebirth", "closure", "transition"],
    emotions: ["release", "uncertainty"],
    lifeAreas: {
      love: 0.5,
      career: 0.6,
      finance: 0.5,
      health: 0.6,
      spiritual: 0.7,
      personal: 0.8,
      advice: 0.7,
    },
    polarity: 0.4,
  },
  {
    cardId: 14,
    name: "Temperance",
    themes: ["balance", "moderation", "integration", "harmony", "healing"],
    emotions: ["calm", "stability"],
    lifeAreas: {
      love: 0.7,
      career: 0.6,
      finance: 0.5,
      health: 0.8,
      spiritual: 0.7,
      personal: 0.7,
      advice: 0.8,
    },
    polarity: 0.8,
  },
  {
    cardId: 15,
    name: "The Devil",
    themes: ["attachment", "temptation", "materialism", "addiction", "bondage"],
    emotions: ["desire", "obsession", "fear"],
    lifeAreas: {
      love: 0.6,
      career: 0.5,
      finance: 0.7,
      health: 0.4,
      spiritual: 0.2,
      personal: 0.4,
      advice: 0.5,
    },
    polarity: 0.2,
  },
  {
    cardId: 16,
    name: "The Tower",
    themes: ["sudden_change", "collapse", "revelation", "shock", "disruption"],
    emotions: ["shock", "fear", "awakening"],
    lifeAreas: {
      love: 0.5,
      career: 0.6,
      finance: 0.5,
      health: 0.4,
      spiritual: 0.6,
      personal: 0.7,
      advice: 0.6,
    },
    polarity: 0.1,
  },
  {
    cardId: 17,
    name: "The Star",
    themes: ["hope", "healing", "renewal", "faith", "guidance"],
    emotions: ["hope", "peace", "relief"],
    lifeAreas: {
      love: 0.7,
      career: 0.5,
      finance: 0.4,
      health: 0.8,
      spiritual: 0.9,
      personal: 0.8,
      advice: 0.7,
    },
    polarity: 0.9,
  },
  {
    cardId: 18,
    name: "The Moon",
    themes: ["illusion", "fear", "uncertainty", "subconscious", "confusion"],
    emotions: ["anxiety", "confusion", "intuition"],
    lifeAreas: {
      love: 0.6,
      career: 0.4,
      finance: 0.3,
      health: 0.5,
      spiritual: 0.7,
      personal: 0.7,
      advice: 0.7,
    },
    polarity: 0.3,
  },
  {
    cardId: 19,
    name: "The Sun",
    themes: ["success", "joy", "clarity", "vitality", "confidence"],
    emotions: ["joy", "optimism", "energy"],
    lifeAreas: {
      love: 0.8,
      career: 0.7,
      finance: 0.6,
      health: 0.9,
      spiritual: 0.6,
      personal: 0.8,
      advice: 0.7,
    },
    polarity: 0.95,
  },
  {
    cardId: 20,
    name: "Judgement",
    themes: ["awakening", "evaluation", "rebirth", "decision", "calling"],
    emotions: ["clarity", "release"],
    lifeAreas: {
      love: 0.6,
      career: 0.7,
      finance: 0.5,
      health: 0.6,
      spiritual: 0.8,
      personal: 0.9,
      advice: 0.8,
    },
    polarity: 0.7,
  },
  {
    cardId: 21,
    name: "The World",
    themes: [
      "completion",
      "achievement",
      "integration",
      "fulfillment",
      "wholeness",
    ],
    emotions: ["satisfaction", "peace", "accomplishment"],
    lifeAreas: {
      love: 0.7,
      career: 0.8,
      finance: 0.7,
      health: 0.7,
      spiritual: 0.8,
      personal: 0.9,
      advice: 0.7,
    },
    polarity: 0.9,
  },
  // 마이너 아르카나
  // 완드
  {
    cardId: 22,
    name: "Ace of Wands",
    themes: ["new_energy", "initiative", "inspiration", "potential"],
    emotions: ["excitement", "motivation"],
    lifeAreas: {
      love: 0.5,
      career: 0.8,
      finance: 0.5,
      health: 0.6,
      spiritual: 0.6,
      personal: 0.8,
      advice: 0.8,
    },
    polarity: 0.8,
  },
  {
    cardId: 23,
    name: "Two of Wands",
    themes: ["planning", "future_direction", "decision", "strategy"],
    emotions: ["anticipation", "confidence"],
    lifeAreas: {
      love: 0.4,
      career: 0.7,
      finance: 0.6,
      health: 0.4,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.8,
    },
    polarity: 0.6,
  },
  {
    cardId: 24,
    name: "Three of Wands",
    themes: ["expansion", "progress", "exploration", "growth"],
    emotions: ["optimism", "expectation"],
    lifeAreas: {
      love: 0.4,
      career: 0.8,
      finance: 0.7,
      health: 0.5,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.7,
    },
    polarity: 0.7,
  },
  {
    cardId: 25,
    name: "Four of Wands",
    themes: ["celebration", "stability", "milestone", "community"],
    emotions: ["joy", "relief"],
    lifeAreas: {
      love: 0.8,
      career: 0.6,
      finance: 0.5,
      health: 0.6,
      spiritual: 0.5,
      personal: 0.7,
      advice: 0.6,
    },
    polarity: 0.85,
  },
  {
    cardId: 26,
    name: "Five of Wands",
    themes: ["competition", "conflict", "tension", "struggle"],
    emotions: ["frustration", "agitation"],
    lifeAreas: {
      love: 0.5,
      career: 0.6,
      finance: 0.4,
      health: 0.4,
      spiritual: 0.3,
      personal: 0.5,
      advice: 0.6,
    },
    polarity: 0.3,
  },
  {
    cardId: 27,
    name: "Six of Wands",
    themes: ["victory", "recognition", "success", "achievement"],
    emotions: ["pride", "confidence"],
    lifeAreas: {
      love: 0.6,
      career: 0.9,
      finance: 0.7,
      health: 0.6,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.7,
    },
    polarity: 0.9,
  },
  {
    cardId: 28,
    name: "Seven of Wands",
    themes: ["defense", "challenge", "perseverance", "pressure"],
    emotions: ["stress", "determination"],
    lifeAreas: {
      love: 0.4,
      career: 0.7,
      finance: 0.5,
      health: 0.5,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.8,
    },
    polarity: 0.5,
  },
  {
    cardId: 29,
    name: "Eight of Wands",
    themes: ["speed", "movement", "progress", "communication"],
    emotions: ["excitement", "urgency"],
    lifeAreas: {
      love: 0.7,
      career: 0.7,
      finance: 0.6,
      health: 0.5,
      spiritual: 0.4,
      personal: 0.6,
      advice: 0.7,
    },
    polarity: 0.8,
  },
  {
    cardId: 30,
    name: "Nine of Wands",
    themes: ["resilience", "persistence", "fatigue", "defense"],
    emotions: ["exhaustion", "determination"],
    lifeAreas: {
      love: 0.4,
      career: 0.6,
      finance: 0.4,
      health: 0.5,
      spiritual: 0.4,
      personal: 0.8,
      advice: 0.7,
    },
    polarity: 0.4,
  },
  {
    cardId: 31,
    name: "Ten of Wands",
    themes: ["burden", "overwork", "responsibility", "stress"],
    emotions: ["pressure", "fatigue"],
    lifeAreas: {
      love: 0.4,
      career: 0.7,
      finance: 0.5,
      health: 0.4,
      spiritual: 0.3,
      personal: 0.5,
      advice: 0.7,
    },
    polarity: 0.2,
  },
  {
    cardId: 32,
    name: "Page of Wands",
    themes: ["curiosity", "exploration", "learning", "enthusiasm"],
    emotions: ["excitement", "curiosity"],
    lifeAreas: {
      love: 0.5,
      career: 0.7,
      finance: 0.4,
      health: 0.5,
      spiritual: 0.5,
      personal: 0.8,
      advice: 0.8,
    },
    polarity: 0.7,
  },
  {
    cardId: 33,
    name: "Knight of Wands",
    themes: ["action", "adventure", "impulsiveness", "drive"],
    emotions: ["passion", "impulse"],
    lifeAreas: {
      love: 0.7,
      career: 0.8,
      finance: 0.5,
      health: 0.6,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.6,
    },
    polarity: 0.7,
  },
  {
    cardId: 34,
    name: "Queen of Wands",
    themes: ["confidence", "charisma", "leadership", "independence"],
    emotions: ["confidence", "warmth"],
    lifeAreas: {
      love: 0.7,
      career: 0.8,
      finance: 0.6,
      health: 0.6,
      spiritual: 0.5,
      personal: 0.8,
      advice: 0.7,
    },
    polarity: 0.85,
  },
  {
    cardId: 35,
    name: "King of Wands",
    themes: ["vision", "leadership", "authority", "strategy"],
    emotions: ["confidence", "determination"],
    lifeAreas: {
      love: 0.6,
      career: 0.9,
      finance: 0.8,
      health: 0.6,
      spiritual: 0.5,
      personal: 0.8,
      advice: 0.8,
    },
    polarity: 0.9,
  },
  // 소드
  {
    cardId: 50,
    name: "Ace of Swords",
    themes: ["clarity", "truth", "breakthrough", "decision"],
    emotions: ["determination", "focus"],
    lifeAreas: {
      love: 0.5,
      career: 0.7,
      finance: 0.6,
      health: 0.5,
      spiritual: 0.5,
      personal: 0.7,
      advice: 0.9,
    },
    polarity: 0.7,
  },
  {
    cardId: 51,
    name: "Two of Swords",
    themes: ["stalemate", "denial", "indecision", "avoidance"],
    emotions: ["tension", "uncertainty"],
    lifeAreas: {
      love: 0.6,
      career: 0.5,
      finance: 0.4,
      health: 0.5,
      spiritual: 0.4,
      personal: 0.6,
      advice: 0.7,
    },
    polarity: 0.3,
  },
  {
    cardId: 52,
    name: "Three of Swords",
    themes: ["heartbreak", "separation", "pain", "truth"],
    emotions: ["sadness", "grief"],
    lifeAreas: {
      love: 0.9,
      career: 0.4,
      finance: 0.3,
      health: 0.4,
      spiritual: 0.4,
      personal: 0.6,
      advice: 0.5,
    },
    polarity: 0.1,
  },
  {
    cardId: 53,
    name: "Four of Swords",
    themes: ["rest", "recovery", "pause", "reflection"],
    emotions: ["calm", "fatigue"],
    lifeAreas: {
      love: 0.4,
      career: 0.4,
      finance: 0.4,
      health: 0.8,
      spiritual: 0.6,
      personal: 0.7,
      advice: 0.8,
    },
    polarity: 0.6,
  },
  {
    cardId: 54,
    name: "Five of Swords",
    themes: ["conflict", "loss", "selfishness", "tension"],
    emotions: ["anger", "resentment"],
    lifeAreas: {
      love: 0.6,
      career: 0.5,
      finance: 0.4,
      health: 0.4,
      spiritual: 0.3,
      personal: 0.5,
      advice: 0.6,
    },
    polarity: 0.2,
  },
  {
    cardId: 55,
    name: "Six of Swords",
    themes: ["transition", "moving_on", "recovery", "distance"],
    emotions: ["relief", "detachment"],
    lifeAreas: {
      love: 0.6,
      career: 0.5,
      finance: 0.5,
      health: 0.6,
      spiritual: 0.6,
      personal: 0.7,
      advice: 0.8,
    },
    polarity: 0.6,
  },
  {
    cardId: 56,
    name: "Seven of Swords",
    themes: ["deception", "strategy", "secrecy", "avoidance"],
    emotions: ["anxiety", "suspicion"],
    lifeAreas: {
      love: 0.7,
      career: 0.6,
      finance: 0.6,
      health: 0.4,
      spiritual: 0.3,
      personal: 0.5,
      advice: 0.6,
    },
    polarity: 0.2,
  },
  {
    cardId: 57,
    name: "Eight of Swords",
    themes: ["restriction", "fear", "limitation", "mental_trap"],
    emotions: ["anxiety", "helplessness"],
    lifeAreas: {
      love: 0.6,
      career: 0.5,
      finance: 0.4,
      health: 0.5,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.7,
    },
    polarity: 0.2,
  },
  {
    cardId: 58,
    name: "Nine of Swords",
    themes: ["worry", "guilt", "stress", "nightmare"],
    emotions: ["fear", "anxiety", "regret"],
    lifeAreas: {
      love: 0.6,
      career: 0.5,
      finance: 0.4,
      health: 0.7,
      spiritual: 0.3,
      personal: 0.8,
      advice: 0.7,
    },
    polarity: 0.1,
  },
  {
    cardId: 59,
    name: "Ten of Swords",
    themes: ["ending", "collapse", "betrayal", "finality"],
    emotions: ["shock", "despair"],
    lifeAreas: {
      love: 0.7,
      career: 0.6,
      finance: 0.5,
      health: 0.5,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.6,
    },
    polarity: 0.1,
  },
  {
    cardId: 60,
    name: "Page of Swords",
    themes: ["curiosity", "observation", "learning", "alertness"],
    emotions: ["curiosity", "alertness"],
    lifeAreas: {
      love: 0.5,
      career: 0.6,
      finance: 0.4,
      health: 0.5,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.8,
    },
    polarity: 0.6,
  },
  {
    cardId: 61,
    name: "Knight of Swords",
    themes: ["speed", "aggression", "decisiveness", "action"],
    emotions: ["determination", "intensity"],
    lifeAreas: {
      love: 0.5,
      career: 0.8,
      finance: 0.6,
      health: 0.5,
      spiritual: 0.3,
      personal: 0.6,
      advice: 0.7,
    },
    polarity: 0.6,
  },
  {
    cardId: 62,
    name: "Queen of Swords",
    themes: ["independence", "clarity", "perception", "truth"],
    emotions: ["calm", "objectivity"],
    lifeAreas: {
      love: 0.6,
      career: 0.7,
      finance: 0.6,
      health: 0.5,
      spiritual: 0.4,
      personal: 0.8,
      advice: 0.9,
    },
    polarity: 0.7,
  },
  {
    cardId: 63,
    name: "King of Swords",
    themes: ["authority", "logic", "strategy", "judgment"],
    emotions: ["confidence", "control"],
    lifeAreas: {
      love: 0.5,
      career: 0.9,
      finance: 0.7,
      health: 0.5,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.9,
    },
    polarity: 0.8,
  },
  {
    cardId: 64,
    name: "Ace of Cups",
    themes: [
      "new_emotion",
      "love_beginning",
      "compassion",
      "emotional_openness",
    ],
    emotions: ["love", "joy", "tenderness"],
    lifeAreas: {
      love: 0.95,
      career: 0.4,
      finance: 0.3,
      health: 0.6,
      spiritual: 0.8,
      personal: 0.8,
      advice: 0.7,
    },
    polarity: 0.9,
  },
  {
    cardId: 65,
    name: "Two of Cups",
    themes: ["union", "partnership", "mutual_attraction", "connection"],
    emotions: ["affection", "trust"],
    lifeAreas: {
      love: 0.95,
      career: 0.6,
      finance: 0.4,
      health: 0.6,
      spiritual: 0.6,
      personal: 0.7,
      advice: 0.7,
    },
    polarity: 0.9,
  },
  {
    cardId: 66,
    name: "Three of Cups",
    themes: ["celebration", "friendship", "community", "shared_joy"],
    emotions: ["happiness", "excitement"],
    lifeAreas: {
      love: 0.7,
      career: 0.5,
      finance: 0.4,
      health: 0.6,
      spiritual: 0.5,
      personal: 0.7,
      advice: 0.6,
    },
    polarity: 0.85,
  },
  {
    cardId: 67,
    name: "Four of Cups",
    themes: ["apathy", "emotional_block", "dissatisfaction", "introspection"],
    emotions: ["boredom", "detachment"],
    lifeAreas: {
      love: 0.6,
      career: 0.4,
      finance: 0.3,
      health: 0.5,
      spiritual: 0.6,
      personal: 0.7,
      advice: 0.7,
    },
    polarity: 0.3,
  },
  {
    cardId: 68,
    name: "Five of Cups",
    themes: ["loss", "regret", "grief", "emotional_setback"],
    emotions: ["sadness", "disappointment"],
    lifeAreas: {
      love: 0.8,
      career: 0.4,
      finance: 0.3,
      health: 0.4,
      spiritual: 0.5,
      personal: 0.7,
      advice: 0.6,
    },
    polarity: 0.2,
  },
  {
    cardId: 69,
    name: "Six of Cups",
    themes: ["nostalgia", "memory", "childhood", "kindness"],
    emotions: ["warmth", "sentimentality"],
    lifeAreas: {
      love: 0.8,
      career: 0.4,
      finance: 0.3,
      health: 0.5,
      spiritual: 0.6,
      personal: 0.7,
      advice: 0.6,
    },
    polarity: 0.75,
  },
  {
    cardId: 70,
    name: "Seven of Cups",
    themes: ["illusion", "choices", "fantasy", "confusion"],
    emotions: ["confusion", "temptation"],
    lifeAreas: {
      love: 0.7,
      career: 0.5,
      finance: 0.4,
      health: 0.4,
      spiritual: 0.6,
      personal: 0.7,
      advice: 0.8,
    },
    polarity: 0.4,
  },
  {
    cardId: 71,
    name: "Eight of Cups",
    themes: ["withdrawal", "leaving", "search_for_meaning", "transition"],
    emotions: ["disappointment", "determination"],
    lifeAreas: {
      love: 0.7,
      career: 0.5,
      finance: 0.4,
      health: 0.5,
      spiritual: 0.8,
      personal: 0.8,
      advice: 0.8,
    },
    polarity: 0.4,
  },
  {
    cardId: 72,
    name: "Nine of Cups",
    themes: ["satisfaction", "wish_fulfillment", "pleasure", "contentment"],
    emotions: ["joy", "satisfaction"],
    lifeAreas: {
      love: 0.8,
      career: 0.6,
      finance: 0.6,
      health: 0.7,
      spiritual: 0.6,
      personal: 0.7,
      advice: 0.6,
    },
    polarity: 0.9,
  },
  {
    cardId: 73,
    name: "Ten of Cups",
    themes: [
      "emotional_fulfillment",
      "family_harmony",
      "lasting_happiness",
      "unity",
    ],
    emotions: ["joy", "peace", "love"],
    lifeAreas: {
      love: 0.95,
      career: 0.5,
      finance: 0.6,
      health: 0.7,
      spiritual: 0.7,
      personal: 0.8,
      advice: 0.6,
    },
    polarity: 0.95,
  },
  {
    cardId: 74,
    name: "Page of Cups",
    themes: ["emotional_message", "creativity", "sensitivity", "curiosity"],
    emotions: ["wonder", "affection"],
    lifeAreas: {
      love: 0.8,
      career: 0.5,
      finance: 0.3,
      health: 0.5,
      spiritual: 0.7,
      personal: 0.8,
      advice: 0.7,
    },
    polarity: 0.75,
  },
  {
    cardId: 75,
    name: "Knight of Cups",
    themes: ["romance", "idealism", "emotional_pursuit", "charm"],
    emotions: ["passion", "romance"],
    lifeAreas: {
      love: 0.9,
      career: 0.5,
      finance: 0.4,
      health: 0.5,
      spiritual: 0.6,
      personal: 0.7,
      advice: 0.6,
    },
    polarity: 0.8,
  },
  {
    cardId: 76,
    name: "Queen of Cups",
    themes: ["empathy", "emotional_intelligence", "care", "intuition"],
    emotions: ["compassion", "calm"],
    lifeAreas: {
      love: 0.9,
      career: 0.6,
      finance: 0.4,
      health: 0.6,
      spiritual: 0.8,
      personal: 0.9,
      advice: 0.8,
    },
    polarity: 0.9,
  },
  {
    cardId: 77,
    name: "King of Cups",
    themes: ["emotional_balance", "wisdom", "control", "compassion"],
    emotions: ["calm", "stability"],
    lifeAreas: {
      love: 0.85,
      career: 0.7,
      finance: 0.5,
      health: 0.6,
      spiritual: 0.7,
      personal: 0.8,
      advice: 0.8,
    },
    polarity: 0.85,
  },
  // 펜타클
  {
    cardId: 78,
    name: "Ace of Pentacles",
    themes: [
      "new_opportunity",
      "material_beginning",
      "investment",
      "prosperity",
    ],
    emotions: ["hope", "anticipation"],
    lifeAreas: {
      love: 0.4,
      career: 0.8,
      finance: 0.95,
      health: 0.6,
      spiritual: 0.4,
      personal: 0.6,
      advice: 0.8,
    },
    polarity: 0.9,
  },
  {
    cardId: 79,
    name: "Two of Pentacles",
    themes: ["balance", "adaptation", "priorities", "time_management"],
    emotions: ["stress", "flexibility"],
    lifeAreas: {
      love: 0.5,
      career: 0.7,
      finance: 0.8,
      health: 0.5,
      spiritual: 0.3,
      personal: 0.6,
      advice: 0.8,
    },
    polarity: 0.6,
  },
  {
    cardId: 80,
    name: "Three of Pentacles",
    themes: ["teamwork", "collaboration", "skill_development", "craftsmanship"],
    emotions: ["motivation", "focus"],
    lifeAreas: {
      love: 0.4,
      career: 0.9,
      finance: 0.7,
      health: 0.5,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.8,
    },
    polarity: 0.8,
  },
  {
    cardId: 81,
    name: "Four of Pentacles",
    themes: ["control", "security", "conservation", "possessiveness"],
    emotions: ["fear", "caution"],
    lifeAreas: {
      love: 0.5,
      career: 0.6,
      finance: 0.8,
      health: 0.5,
      spiritual: 0.3,
      personal: 0.5,
      advice: 0.7,
    },
    polarity: 0.4,
  },
  {
    cardId: 82,
    name: "Five of Pentacles",
    themes: ["poverty", "hardship", "loss", "isolation"],
    emotions: ["anxiety", "despair"],
    lifeAreas: {
      love: 0.5,
      career: 0.6,
      finance: 0.9,
      health: 0.6,
      spiritual: 0.4,
      personal: 0.5,
      advice: 0.7,
    },
    polarity: 0.1,
  },
  {
    cardId: 83,
    name: "Six of Pentacles",
    themes: ["generosity", "sharing", "charity", "financial_balance"],
    emotions: ["gratitude", "kindness"],
    lifeAreas: {
      love: 0.6,
      career: 0.6,
      finance: 0.8,
      health: 0.5,
      spiritual: 0.5,
      personal: 0.6,
      advice: 0.8,
    },
    polarity: 0.8,
  },
  {
    cardId: 84,
    name: "Seven of Pentacles",
    themes: ["evaluation", "long_term_growth", "patience", "investment"],
    emotions: ["patience", "reflection"],
    lifeAreas: {
      love: 0.4,
      career: 0.8,
      finance: 0.8,
      health: 0.5,
      spiritual: 0.4,
      personal: 0.6,
      advice: 0.8,
    },
    polarity: 0.6,
  },
  {
    cardId: 85,
    name: "Eight of Pentacles",
    themes: ["dedication", "skill_building", "hard_work", "practice"],
    emotions: ["focus", "determination"],
    lifeAreas: {
      love: 0.3,
      career: 0.95,
      finance: 0.8,
      health: 0.5,
      spiritual: 0.3,
      personal: 0.7,
      advice: 0.9,
    },
    polarity: 0.8,
  },
  {
    cardId: 86,
    name: "Nine of Pentacles",
    themes: ["independence", "luxury", "self_sufficiency", "reward"],
    emotions: ["satisfaction", "confidence"],
    lifeAreas: {
      love: 0.6,
      career: 0.7,
      finance: 0.9,
      health: 0.6,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.7,
    },
    polarity: 0.9,
  },
  {
    cardId: 87,
    name: "Ten of Pentacles",
    themes: ["wealth", "legacy", "family_security", "long_term_success"],
    emotions: ["security", "fulfillment"],
    lifeAreas: {
      love: 0.7,
      career: 0.7,
      finance: 0.95,
      health: 0.6,
      spiritual: 0.4,
      personal: 0.6,
      advice: 0.7,
    },
    polarity: 0.95,
  },
  {
    cardId: 88,
    name: "Page of Pentacles",
    themes: ["learning", "new_skill", "practical_growth", "curiosity"],
    emotions: ["curiosity", "motivation"],
    lifeAreas: {
      love: 0.4,
      career: 0.8,
      finance: 0.7,
      health: 0.5,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.8,
    },
    polarity: 0.7,
  },
  {
    cardId: 89,
    name: "Knight of Pentacles",
    themes: ["discipline", "routine", "reliability", "steady_progress"],
    emotions: ["focus", "patience"],
    lifeAreas: {
      love: 0.5,
      career: 0.85,
      finance: 0.85,
      health: 0.6,
      spiritual: 0.3,
      personal: 0.7,
      advice: 0.9,
    },
    polarity: 0.8,
  },
  {
    cardId: 90,
    name: "Queen of Pentacles",
    themes: ["care", "practicality", "security", "nurturing"],
    emotions: ["warmth", "stability"],
    lifeAreas: {
      love: 0.7,
      career: 0.7,
      finance: 0.8,
      health: 0.7,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.8,
    },
    polarity: 0.9,
  },
  {
    cardId: 91,
    name: "King of Pentacles",
    themes: ["wealth_mastery", "stability", "leadership", "financial_success"],
    emotions: ["confidence", "security"],
    lifeAreas: {
      love: 0.6,
      career: 0.9,
      finance: 0.95,
      health: 0.7,
      spiritual: 0.4,
      personal: 0.7,
      advice: 0.9,
    },
    polarity: 0.95,
  },
];

// 하위 호환을 위해 레거시 export를 유지하고 정규화 별칭을 제공합니다.
const normalizeSemanticCardId = (legacyCardId: number): number => {
  // 레거시 파일은 컵(64~77), 펜타클(78~91) ID가 밀려 있어 정규화가 필요합니다.
  if (legacyCardId >= 78) return legacyCardId - 14; // 78~91 -> 64~77
  if (legacyCardId >= 64 && legacyCardId <= 77) return legacyCardId - 28; // 64~77 -> 36~49
  return legacyCardId;
};

export const SEMANTIC_TAGS = SEMENTIG_TAG.map((entry) => ({
  ...entry,
  cardId: normalizeSemanticCardId(entry.cardId),
  legacyCardId: entry.cardId,
}));

// 자주 발생하는 오타 호환 별칭을 함께 제공합니다.
export const SEMENTIC_TAG = SEMANTIC_TAGS;
export const SEMANTIC_TAG = SEMANTIC_TAGS;





