// 1. TypeScript Interface 정의

// 2. 이미지 자원 매핑 (Mapping)
// 현재 구조에는 카드 이미지 경로가 없습니다. id나 name을 기반으로 이미지 파일명을 규칙화(예: card_0.png)하거나, 데이터 내에 image_url 속성을 추가하면 UI 렌더링 시 훨씬 편해집니다.

// 3. 정역방향(Upright/Reversed) 구분
// 현재 light_keywords와 shadow_keywords가 그 역할을 어느 정도 대신하고 있지만, 실제 타로 앱에서는 카드가 뒤집혀 나오는 경우가 많습니다.
// - 대안: AI 프롬프트에 전달할 때 isReversed: boolean 상태에 따라 어떤 키워드군을 우선적으로 참조할지 결정하는 로직을 추가하면 좋습니다

// 4. 프롬프트 토큰 최적화
// AI(Gemini 등)에게 이 데이터를 통째로 넘기면 토큰 소모가 큽니다.
// - 대안: 사용자가 뽑은 3장의 카드 데이터만 필터링해서 프롬프트에 포함시키는 getPromptContext(cardIds: number[]) 같은 헬퍼 함수를 작성해 두는 것을 추천합니다.

// ### 추가 제안: 다국어 지원 (i18n)
// 현재 텍스트가 한국어로 고정되어 있습니다. 나중에 영어 버전 등을 고려하신다면, 텍스트 필드들을 객체화하거나 별도의 번역 리소스로 분리하는 것도 유지보수에 큰 도움이 됩니다.

// // 기본 카드 해석, AI 프롬프트 기본 데이터
export const TAROT_MEANINGS = [
  // Major Arcana
  {
    id: 0,
    name: "The Fool",
    arcana: "major",
    number: 0,
    core_keywords: ["새로운 시작", "순수", "모험", "가능성"],
    light_keywords: ["자유", "도전", "창의성", "신뢰"],
    shadow_keywords: ["무모함", "준비 부족", "충동"],
    love: ["새로운 연애 시작", "가벼운 관계", "자유로운 사랑"],
    career: ["새로운 프로젝트", "스타트업", "도전적 선택"],
    finance: ["위험 투자", "충동 소비"],
    health: ["에너지 상승", "활동 시작"],
    spiritual: ["영적 여정의 시작"],
    advice: ["두려움보다 호기심을 따르라"],
  },

  {
    id: 1,
    name: "The Magician",
    arcana: "major",
    number: 1,
    core_keywords: ["창조", "의지", "실현", "능력"],
    light_keywords: ["집중", "능력 활용", "자기 확신"],
    shadow_keywords: ["조작", "속임수", "허세"],
    love: ["매력적인 사람", "주도적 관계"],
    career: ["능력 발휘", "사업 시작"],
    finance: ["수익 창출 능력"],
    health: ["회복력", "의지력"],
    spiritual: ["의도와 현실 창조"],
    advice: ["이미 가진 능력을 활용하라"],
  },

  {
    id: 2,
    name: "The High Priestess",
    arcana: "major",
    number: 2,
    core_keywords: ["직관", "비밀", "내면"],
    light_keywords: ["지혜", "통찰", "영감"],
    shadow_keywords: ["숨겨진 정보", "소극성"],
    love: ["비밀스러운 감정", "조용한 관계"],
    career: ["정보 분석", "연구"],
    finance: ["숨겨진 재정 정보"],
    health: ["정신적 휴식 필요"],
    spiritual: ["직관 강화"],
    advice: ["겉보다 내면의 목소리를 들어라"],
  },

  {
    id: 3,
    name: "The Empress",
    arcana: "major",
    number: 3,
    core_keywords: ["풍요", "창조", "성장"],
    light_keywords: ["사랑", "돌봄", "번영"],
    shadow_keywords: ["의존", "과보호"],
    love: ["풍요로운 사랑", "임신 가능성"],
    career: ["창조적 프로젝트"],
    finance: ["풍요로운 흐름"],
    health: ["생명력 상승"],
    spiritual: ["자연과 연결"],
    advice: ["성장을 허용하라"],
  },

  {
    id: 4,
    name: "The Emperor",
    arcana: "major",
    number: 4,
    core_keywords: ["권위", "질서", "안정"],
    light_keywords: ["리더십", "구조", "책임"],
    shadow_keywords: ["통제", "완고함"],
    love: ["안정적 관계", "책임 있는 파트너"],
    career: ["관리직", "조직 구축"],
    finance: ["안정적 재정"],
    health: ["체력 관리"],
    spiritual: ["현실 기반 성장"],
    advice: ["질서를 세워라"],
  },

  {
    id: 5,
    name: "The Hierophant",
    arcana: "major",
    number: 5,
    core_keywords: ["전통", "가르침", "신념"],
    light_keywords: ["멘토", "지혜", "교육"],
    shadow_keywords: ["보수성", "고정관념"],
    love: ["전통적 관계", "결혼"],
    career: ["교육", "기관"],
    finance: ["안정적 재정 규칙"],
    health: ["전통 치료"],
    spiritual: ["종교적 길"],
    advice: ["지혜로운 조언을 구하라"],
  },

  {
    id: 6,
    name: "The Lovers",
    arcana: "major",
    number: 6,
    core_keywords: ["선택", "사랑", "조화"],
    light_keywords: ["연결", "신뢰", "결합"],
    shadow_keywords: ["갈등", "유혹"],
    love: ["진지한 사랑", "중요한 선택"],
    career: ["협력 관계"],
    finance: ["파트너십 재정"],
    health: ["균형 필요"],
    spiritual: ["영혼의 연결"],
    advice: ["진심을 기준으로 선택하라"],
  },

  {
    id: 7,
    name: "The Chariot",
    arcana: "major",
    number: 7,
    core_keywords: ["의지", "전진", "승리"],
    light_keywords: ["집중", "결단", "통제"],
    shadow_keywords: ["충돌", "과속"],
    love: ["관계 주도"],
    career: ["목표 달성"],
    finance: ["성공적 추진"],
    health: ["활력 증가"],
    spiritual: ["의지 강화"],
    advice: ["방향을 잃지 마라"],
  },

  {
    id: 8,
    name: "Strength",
    arcana: "major",
    number: 8,
    core_keywords: ["내면 힘", "용기", "인내"],
    light_keywords: ["자제력", "부드러운 힘"],
    shadow_keywords: ["감정 억압"],
    love: ["헌신", "인내"],
    career: ["지속적 노력"],
    finance: ["안정적 관리"],
    health: ["회복력"],
    spiritual: ["내면 성장"],
    advice: ["부드러운 힘을 사용하라"],
  },

  {
    id: 9,
    name: "The Hermit",
    arcana: "major",
    number: 9,
    core_keywords: ["고독", "탐구", "지혜"],
    light_keywords: ["성찰", "내면 탐색"],
    shadow_keywords: ["고립", "외로움"],
    love: ["거리 두기"],
    career: ["연구", "전문성"],
    finance: ["절약"],
    health: ["휴식 필요"],
    spiritual: ["깨달음"],
    advice: ["혼자 생각할 시간을 가져라"],
  },

  {
    id: 10,
    name: "Wheel of Fortune",
    arcana: "major",
    number: 10,
    core_keywords: ["변화", "운명", "순환"],
    light_keywords: ["행운", "기회"],
    shadow_keywords: ["불안정"],
    love: ["관계 변화"],
    career: ["예상 못한 기회"],
    finance: ["재정 변동"],
    health: ["상태 변화"],
    spiritual: ["운명의 흐름"],
    advice: ["변화를 받아들여라"],
  },

  {
    id: 11,
    name: "Justice",
    arcana: "major",
    number: 11,
    core_keywords: ["균형", "정의", "결과"],
    light_keywords: ["공정", "진실"],
    shadow_keywords: ["불균형", "편향"],
    love: ["공정한 관계"],
    career: ["법적 문제"],
    finance: ["계약", "정산"],
    health: ["균형 필요"],
    spiritual: ["카르마"],
    advice: ["정직하게 행동하라"],
  },

  {
    id: 12,
    name: "The Hanged Man",
    arcana: "major",
    number: 12,
    core_keywords: ["희생", "관점 변화", "정지"],
    light_keywords: ["깨달음", "수용"],
    shadow_keywords: ["정체", "무력감"],
    love: ["기다림"],
    career: ["지연"],
    finance: ["투자 보류"],
    health: ["휴식 필요"],
    spiritual: ["새로운 시각"],
    advice: ["관점을 바꿔라"],
  },

  {
    id: 13,
    name: "Death",
    arcana: "major",
    number: 13,
    core_keywords: ["종결", "변화", "재생"],
    light_keywords: ["재탄생", "정리"],
    shadow_keywords: ["저항", "두려움"],
    love: ["관계 종료 또는 변화"],
    career: ["직업 변화"],
    finance: ["재정 재구성"],
    health: ["생활 습관 변화"],
    spiritual: ["변형"],
    advice: ["끝은 새로운 시작이다"],
  },

  {
    id: 14,
    name: "Temperance",
    arcana: "major",
    number: 14,
    core_keywords: ["균형", "조화", "조절"],
    light_keywords: ["협력", "안정"],
    shadow_keywords: ["극단"],
    love: ["안정된 관계"],
    career: ["협업"],
    finance: ["재정 균형"],
    health: ["생활 균형"],
    spiritual: ["내적 평화"],
    advice: ["균형을 유지하라"],
  },

  {
    id: 15,
    name: "The Devil",
    arcana: "major",
    number: 15,
    core_keywords: ["집착", "유혹", "속박"],
    light_keywords: ["욕망 인식"],
    shadow_keywords: ["중독", "통제"],
    love: ["집착적 관계"],
    career: ["물질 중심"],
    finance: ["빚"],
    health: ["나쁜 습관"],
    spiritual: ["자유 필요"],
    advice: ["속박을 인식하라"],
  },

  {
    id: 16,
    name: "The Tower",
    arcana: "major",
    number: 16,
    core_keywords: ["붕괴", "충격", "각성"],
    light_keywords: ["진실 드러남"],
    shadow_keywords: ["위기"],
    love: ["관계 충격"],
    career: ["구조 붕괴"],
    finance: ["예상 못한 손실"],
    health: ["급격한 변화"],
    spiritual: ["각성"],
    advice: ["변화를 받아들여라"],
  },

  {
    id: 17,
    name: "The Star",
    arcana: "major",
    number: 17,
    core_keywords: ["희망", "치유", "영감"],
    light_keywords: ["평온", "신뢰"],
    shadow_keywords: ["희망 상실"],
    love: ["치유 관계"],
    career: ["새로운 영감"],
    finance: ["회복"],
    health: ["회복"],
    spiritual: ["영적 인도"],
    advice: ["희망을 잃지 마라"],
  },

  {
    id: 18,
    name: "The Moon",
    arcana: "major",
    number: 18,
    core_keywords: ["환상", "불안", "무의식"],
    light_keywords: ["상상력"],
    shadow_keywords: ["혼란", "착각"],
    love: ["불확실한 감정"],
    career: ["불명확 상황"],
    finance: ["숨겨진 위험"],
    health: ["정신적 불안"],
    spiritual: ["무의식 탐구"],
    advice: ["사실을 확인하라"],
  },

  {
    id: 19,
    name: "The Sun",
    arcana: "major",
    number: 19,
    core_keywords: ["성공", "기쁨", "에너지"],
    light_keywords: ["행복", "성취"],
    shadow_keywords: ["과신"],
    love: ["행복한 관계"],
    career: ["성공"],
    finance: ["재정 증가"],
    health: ["활력"],
    spiritual: ["긍정 에너지"],
    advice: ["자신감을 가져라"],
  },

  {
    id: 20,
    name: "Judgement",
    arcana: "major",
    number: 20,
    core_keywords: ["각성", "결정", "부활"],
    light_keywords: ["깨달음", "새 시작"],
    shadow_keywords: ["후회"],
    love: ["관계 재평가"],
    career: ["중요 결정"],
    finance: ["재정 정리"],
    health: ["재생"],
    spiritual: ["영적 각성"],
    advice: ["과거를 정리하라"],
  },

  {
    id: 21,
    name: "The World",
    arcana: "major",
    number: 21,
    core_keywords: ["완성", "성취", "통합"],
    light_keywords: ["목표 달성", "성공"],
    shadow_keywords: ["마무리 지연"],
    love: ["완전한 관계"],
    career: ["프로젝트 완료"],
    finance: ["안정"],
    health: ["균형"],
    spiritual: ["완성 단계"],
    advice: ["성취를 받아들여라"],
  },
  // Minor Arcana
  // Wands
  {
    id: 22,
    name: "Ace of Wands",
    arcana: "minor",
    number: 1,
    core_keywords: ["새로운 열정", "창조 에너지", "시작"],
    light_keywords: ["영감", "동기", "가능성"],
    shadow_keywords: ["충동", "에너지 낭비"],
    love: ["새로운 로맨스 시작", "강한 끌림"],
    career: ["새 프로젝트 시작", "창업 아이디어"],
    finance: ["새로운 수익 기회"],
    health: ["활력 상승"],
    spiritual: ["창조 에너지 활성화"],
    advice: ["떠오른 아이디어를 행동으로 옮겨라"],
  },

  {
    id: 23,
    name: "Two of Wands",
    arcana: "minor",
    number: 2,
    core_keywords: ["계획", "선택", "미래 방향"],
    light_keywords: ["전략", "가능성 탐색"],
    shadow_keywords: ["망설임", "결정 지연"],
    love: ["관계의 미래 고민"],
    career: ["장기 계획 수립"],
    finance: ["투자 계획"],
    health: ["생활 계획 필요"],
    spiritual: ["목표 설정"],
    advice: ["멀리 보고 계획하라"],
  },

  {
    id: 24,
    name: "Three of Wands",
    arcana: "minor",
    number: 3,
    core_keywords: ["확장", "성장", "기회"],
    light_keywords: ["진전", "협력"],
    shadow_keywords: ["지연", "기대 실패"],
    love: ["관계 발전"],
    career: ["사업 확장"],
    finance: ["투자 성장"],
    health: ["점진적 개선"],
    spiritual: ["의식 확장"],
    advice: ["기회를 기다리며 준비하라"],
  },

  {
    id: 25,
    name: "Four of Wands",
    arcana: "minor",
    number: 4,
    core_keywords: ["안정", "축하", "조화"],
    light_keywords: ["성취", "평화"],
    shadow_keywords: ["안정 부족"],
    love: ["결혼", "관계 안정"],
    career: ["프로젝트 성공"],
    finance: ["안정적 수입"],
    health: ["안정 상태"],
    spiritual: ["조화로운 상태"],
    advice: ["성취를 기념하라"],
  },

  {
    id: 26,
    name: "Five of Wands",
    arcana: "minor",
    number: 5,
    core_keywords: ["경쟁", "갈등", "도전"],
    light_keywords: ["성장 경쟁"],
    shadow_keywords: ["불필요한 싸움"],
    love: ["의견 충돌"],
    career: ["직장 경쟁"],
    finance: ["재정 경쟁"],
    health: ["스트레스"],
    spiritual: ["내적 갈등"],
    advice: ["갈등을 성장 기회로 삼아라"],
  },

  {
    id: 27,
    name: "Six of Wands",
    arcana: "minor",
    number: 6,
    core_keywords: ["승리", "인정", "성공"],
    light_keywords: ["명예", "자신감"],
    shadow_keywords: ["과시", "자만"],
    love: ["관계에서 인정"],
    career: ["승진", "성과 인정"],
    finance: ["재정 성공"],
    health: ["회복"],
    spiritual: ["자신감 상승"],
    advice: ["성공을 겸손하게 받아들여라"],
  },

  {
    id: 28,
    name: "Seven of Wands",
    arcana: "minor",
    number: 7,
    core_keywords: ["방어", "도전", "경쟁 유지"],
    light_keywords: ["용기", "지키기"],
    shadow_keywords: ["압박", "방어적 태도"],
    love: ["관계 방어"],
    career: ["경쟁 유지"],
    finance: ["재정 보호"],
    health: ["스트레스 관리"],
    spiritual: ["신념 방어"],
    advice: ["자신의 위치를 지켜라"],
  },

  {
    id: 29,
    name: "Eight of Wands",
    arcana: "minor",
    number: 8,
    core_keywords: ["속도", "진전", "소식"],
    light_keywords: ["빠른 발전"],
    shadow_keywords: ["혼란", "과속"],
    love: ["빠른 관계 발전"],
    career: ["프로젝트 급진전"],
    finance: ["빠른 거래"],
    health: ["활동 증가"],
    spiritual: ["에너지 흐름"],
    advice: ["흐름을 활용하라"],
  },

  {
    id: 30,
    name: "Nine of Wands",
    arcana: "minor",
    number: 9,
    core_keywords: ["지속", "방어", "인내"],
    light_keywords: ["끈기", "마지막 노력"],
    shadow_keywords: ["피로", "의심"],
    love: ["관계 피로"],
    career: ["마지막 단계 노력"],
    finance: ["재정 방어"],
    health: ["피로 누적"],
    spiritual: ["시험"],
    advice: ["조금만 더 버텨라"],
  },

  {
    id: 31,
    name: "Ten of Wands",
    arcana: "minor",
    number: 10,
    core_keywords: ["부담", "책임", "과중"],
    light_keywords: ["성과 직전"],
    shadow_keywords: ["과로", "압박"],
    love: ["관계 부담"],
    career: ["업무 과다"],
    finance: ["재정 부담"],
    health: ["피로"],
    spiritual: ["짐 내려놓기"],
    advice: ["책임을 나누어라"],
  },

  {
    id: 32,
    name: "Page of Wands",
    arcana: "minor",
    number: 11,
    core_keywords: ["호기심", "탐험", "새로운 열정"],
    light_keywords: ["학습", "모험"],
    shadow_keywords: ["미숙", "충동"],
    love: ["설레는 시작"],
    career: ["새로운 기회 탐색"],
    finance: ["작은 기회"],
    health: ["활동 시작"],
    spiritual: ["새로운 영적 관심"],
    advice: ["호기심을 따라가라"],
  },

  {
    id: 33,
    name: "Knight of Wands",
    arcana: "minor",
    number: 12,
    core_keywords: ["행동", "열정", "모험"],
    light_keywords: ["추진력", "대담함"],
    shadow_keywords: ["성급함", "불안정"],
    love: ["강렬한 연애"],
    career: ["빠른 추진"],
    finance: ["위험 투자"],
    health: ["활력"],
    spiritual: ["열정적 탐구"],
    advice: ["에너지를 집중하라"],
  },

  {
    id: 34,
    name: "Queen of Wands",
    arcana: "minor",
    number: 13,
    core_keywords: ["자신감", "카리스마", "독립"],
    light_keywords: ["매력", "리더십"],
    shadow_keywords: ["질투", "지배적 태도"],
    love: ["매력적인 파트너"],
    career: ["리더십 발휘"],
    finance: ["안정적 관리"],
    health: ["활력"],
    spiritual: ["자기 확신"],
    advice: ["자신감을 드러내라"],
  },

  {
    id: 35,
    name: "King of Wands",
    arcana: "minor",
    number: 14,
    core_keywords: ["비전", "리더십", "창업"],
    light_keywords: ["전략", "영향력"],
    shadow_keywords: ["독단", "충동적 결정"],
    love: ["주도적 관계"],
    career: ["사업가", "리더"],
    finance: ["사업 확장"],
    health: ["강한 에너지"],
    spiritual: ["비전 실현"],
    advice: ["큰 그림을 보고 이끌어라"],
  },
  // Cups
  {
    id: 36,
    name: "Ace of Cups",
    arcana: "minor",
    number: 1,
    core_keywords: ["사랑", "감정 시작", "감정의 흐름"],
    light_keywords: ["연민", "감정적 충만", "새로운 관계"],
    shadow_keywords: ["감정 억제", "감정 불안"],
    love: ["새로운 사랑", "감정적 연결 시작"],
    career: ["감정적 만족이 있는 일"],
    finance: ["기쁨을 주는 소비"],
    health: ["정서적 치유"],
    spiritual: ["영적 사랑과 연민"],
    advice: ["마음을 열어 감정을 받아들여라"],
  },

  {
    id: 37,
    name: "Two of Cups",
    arcana: "minor",
    number: 2,
    core_keywords: ["연결", "파트너십", "조화"],
    light_keywords: ["상호 이해", "사랑의 균형"],
    shadow_keywords: ["감정 의존", "갈등 가능성"],
    love: ["서로 끌리는 관계", "연애 시작"],
    career: ["협력 관계 형성"],
    finance: ["파트너와 재정 협력"],
    health: ["정서적 안정"],
    spiritual: ["영혼의 연결"],
    advice: ["상대와 진심으로 연결하라"],
  },

  {
    id: 38,
    name: "Three of Cups",
    arcana: "minor",
    number: 3,
    core_keywords: ["축하", "우정", "공동체"],
    light_keywords: ["행복", "사회적 연결"],
    shadow_keywords: ["과도한 즐김", "표면적 관계"],
    love: ["즐거운 연애", "친구 관계에서 발전"],
    career: ["팀워크 성공"],
    finance: ["즐거운 지출"],
    health: ["활력 증가"],
    spiritual: ["감사와 기쁨"],
    advice: ["기쁨을 나누어라"],
  },

  {
    id: 39,
    name: "Four of Cups",
    arcana: "minor",
    number: 4,
    core_keywords: ["무관심", "권태", "내적 고민"],
    light_keywords: ["내면 탐색"],
    shadow_keywords: ["기회 놓침", "감정 침체"],
    love: ["관계에 대한 무관심"],
    career: ["동기 부족"],
    finance: ["기회 무시"],
    health: ["감정적 피로"],
    spiritual: ["내면 성찰"],
    advice: ["새로운 기회를 다시 보라"],
  },

  {
    id: 40,
    name: "Five of Cups",
    arcana: "minor",
    number: 5,
    core_keywords: ["실망", "상실", "후회"],
    light_keywords: ["배움", "감정 정리"],
    shadow_keywords: ["과거 집착"],
    love: ["이별 슬픔"],
    career: ["실패 경험"],
    finance: ["손실"],
    health: ["정서적 스트레스"],
    spiritual: ["상실을 통한 성장"],
    advice: ["남아있는 가능성을 보라"],
  },

  {
    id: 41,
    name: "Six of Cups",
    arcana: "minor",
    number: 6,
    core_keywords: ["추억", "순수", "과거"],
    light_keywords: ["따뜻한 기억", "순수한 관계"],
    shadow_keywords: ["과거 집착"],
    love: ["옛 연인 재회", "순수한 사랑"],
    career: ["옛 인연 도움"],
    finance: ["안정적 흐름"],
    health: ["정서적 안정"],
    spiritual: ["순수함 회복"],
    advice: ["과거에서 배워라"],
  },

  {
    id: 42,
    name: "Seven of Cups",
    arcana: "minor",
    number: 7,
    core_keywords: ["환상", "선택", "혼란"],
    light_keywords: ["상상력", "가능성"],
    shadow_keywords: ["착각", "비현실적 기대"],
    love: ["감정 혼란"],
    career: ["많은 선택"],
    finance: ["위험한 투자"],
    health: ["정신적 혼란"],
    spiritual: ["환상 탐구"],
    advice: ["현실적인 선택을 하라"],
  },

  {
    id: 43,
    name: "Eight of Cups",
    arcana: "minor",
    number: 8,
    core_keywords: ["떠남", "포기", "탐색"],
    light_keywords: ["새로운 길"],
    shadow_keywords: ["회피"],
    love: ["관계에서 떠남"],
    career: ["직업 변화"],
    finance: ["재정 방향 변화"],
    health: ["생활 변화 필요"],
    spiritual: ["영적 탐색"],
    advice: ["더 의미 있는 길을 찾아라"],
  },

  {
    id: 44,
    name: "Nine of Cups",
    arcana: "minor",
    number: 9,
    core_keywords: ["만족", "소원 성취", "기쁨"],
    light_keywords: ["행복", "감정적 풍요"],
    shadow_keywords: ["과욕"],
    love: ["행복한 관계"],
    career: ["목표 달성"],
    finance: ["재정 만족"],
    health: ["좋은 상태"],
    spiritual: ["감사"],
    advice: ["현재의 만족을 즐겨라"],
  },

  {
    id: 45,
    name: "Ten of Cups",
    arcana: "minor",
    number: 10,
    core_keywords: ["행복한 관계", "가족", "조화"],
    light_keywords: ["완전한 사랑", "감정적 안정"],
    shadow_keywords: ["이상화"],
    love: ["행복한 가족 관계"],
    career: ["조화로운 팀"],
    finance: ["안정된 삶"],
    health: ["정서적 안정"],
    spiritual: ["사랑과 평화"],
    advice: ["조화를 유지하라"],
  },

  {
    id: 46,
    name: "Page of Cups",
    arcana: "minor",
    number: 11,
    core_keywords: ["감정 표현", "창의성", "직관"],
    light_keywords: ["로맨틱함", "예술성"],
    shadow_keywords: ["감정 미숙"],
    love: ["로맨틱한 제안"],
    career: ["창의적 기회"],
    finance: ["작은 기쁨"],
    health: ["감정 치유"],
    spiritual: ["직관적 메시지"],
    advice: ["감정을 솔직히 표현하라"],
  },

  {
    id: 47,
    name: "Knight of Cups",
    arcana: "minor",
    number: 12,
    core_keywords: ["로맨스", "이상주의", "추구"],
    light_keywords: ["헌신", "감정 표현"],
    shadow_keywords: ["비현실적 기대"],
    love: ["열정적 구애"],
    career: ["창의적 직업"],
    finance: ["감정 기반 소비"],
    health: ["감정 상태 영향"],
    spiritual: ["영적 추구"],
    advice: ["마음을 따르되 현실도 보라"],
  },

  {
    id: 48,
    name: "Queen of Cups",
    arcana: "minor",
    number: 13,
    core_keywords: ["공감", "직관", "감정 이해"],
    light_keywords: ["연민", "지혜"],
    shadow_keywords: ["감정 과잉"],
    love: ["깊은 이해 관계"],
    career: ["상담", "돌봄 직업"],
    finance: ["신중한 관리"],
    health: ["정서적 안정"],
    spiritual: ["높은 직관"],
    advice: ["감정과 직관을 신뢰하라"],
  },

  {
    id: 49,
    name: "King of Cups",
    arcana: "minor",
    number: 14,
    core_keywords: ["감정 통제", "지혜", "균형"],
    light_keywords: ["성숙한 사랑", "리더십"],
    shadow_keywords: ["감정 억압"],
    love: ["성숙한 파트너"],
    career: ["감정 관리 리더"],
    finance: ["안정적 관리"],
    health: ["정서적 균형"],
    spiritual: ["깊은 이해"],
    advice: ["감정을 균형 있게 다뤄라"],
  },
  // Swords
  {
    id: 50,
    name: "Ace of Swords",
    arcana: "minor",
    number: 1,
    core_keywords: ["진실", "명확성", "새로운 아이디어"],
    light_keywords: ["통찰", "결단", "이성"],
    shadow_keywords: ["갈등 시작", "냉정함"],
    love: ["관계에서 진실 드러남"],
    career: ["새로운 전략", "명확한 판단"],
    finance: ["합리적 결정"],
    health: ["정신적 명확성"],
    spiritual: ["진실 인식"],
    advice: ["진실을 직시하라"],
  },

  {
    id: 51,
    name: "Two of Swords",
    arcana: "minor",
    number: 2,
    core_keywords: ["결정 회피", "균형", "막힌 감정"],
    light_keywords: ["중립 유지"],
    shadow_keywords: ["회피", "부정"],
    love: ["감정적 거리"],
    career: ["결정 지연"],
    finance: ["판단 보류"],
    health: ["스트레스"],
    spiritual: ["내면 갈등"],
    advice: ["결정을 피하지 마라"],
  },

  {
    id: 52,
    name: "Three of Swords",
    arcana: "minor",
    number: 3,
    core_keywords: ["상처", "슬픔", "이별"],
    light_keywords: ["감정 정화"],
    shadow_keywords: ["깊은 상처"],
    love: ["이별", "배신"],
    career: ["실망"],
    finance: ["손실"],
    health: ["정서적 고통"],
    spiritual: ["고통 통한 성장"],
    advice: ["감정을 인정하라"],
  },

  {
    id: 53,
    name: "Four of Swords",
    arcana: "minor",
    number: 4,
    core_keywords: ["휴식", "회복", "멈춤"],
    light_keywords: ["치유", "회복 시간"],
    shadow_keywords: ["정체"],
    love: ["관계 휴식"],
    career: ["재충전 필요"],
    finance: ["지출 절제"],
    health: ["휴식 필요"],
    spiritual: ["명상"],
    advice: ["잠시 멈추어라"],
  },

  {
    id: 54,
    name: "Five of Swords",
    arcana: "minor",
    number: 5,
    core_keywords: ["갈등", "패배", "긴장"],
    light_keywords: ["갈등 인식"],
    shadow_keywords: ["비열한 승리"],
    love: ["다툼"],
    career: ["직장 갈등"],
    finance: ["손해"],
    health: ["스트레스 증가"],
    spiritual: ["에고 갈등"],
    advice: ["불필요한 싸움을 피하라"],
  },

  {
    id: 55,
    name: "Six of Swords",
    arcana: "minor",
    number: 6,
    core_keywords: ["이동", "회복", "전환"],
    light_keywords: ["문제에서 벗어남"],
    shadow_keywords: ["감정적 거리"],
    love: ["관계 변화"],
    career: ["직장 이동"],
    finance: ["안정으로 이동"],
    health: ["회복 단계"],
    spiritual: ["새로운 길"],
    advice: ["더 나은 방향으로 이동하라"],
  },

  {
    id: 56,
    name: "Seven of Swords",
    arcana: "minor",
    number: 7,
    core_keywords: ["속임수", "전략", "비밀 행동"],
    light_keywords: ["지혜로운 전략"],
    shadow_keywords: ["거짓", "배신"],
    love: ["숨기는 행동"],
    career: ["정치적 상황"],
    finance: ["불투명 거래"],
    health: ["숨겨진 문제"],
    spiritual: ["자기 기만"],
    advice: ["정직을 유지하라"],
  },

  {
    id: 57,
    name: "Eight of Swords",
    arcana: "minor",
    number: 8,
    core_keywords: ["속박", "제한", "두려움"],
    light_keywords: ["상황 인식"],
    shadow_keywords: ["자기 제한"],
    love: ["관계에서 답답함"],
    career: ["직장 제한"],
    finance: ["재정 압박"],
    health: ["불안"],
    spiritual: ["자기 인식 필요"],
    advice: ["자신을 제한하는 생각을 깨라"],
  },

  {
    id: 58,
    name: "Nine of Swords",
    arcana: "minor",
    number: 9,
    core_keywords: ["불안", "걱정", "악몽"],
    light_keywords: ["문제 인식"],
    shadow_keywords: ["극심한 스트레스"],
    love: ["관계 걱정"],
    career: ["압박감"],
    finance: ["재정 걱정"],
    health: ["불면"],
    spiritual: ["내면 두려움"],
    advice: ["걱정을 현실적으로 보라"],
  },

  {
    id: 59,
    name: "Ten of Swords",
    arcana: "minor",
    number: 10,
    core_keywords: ["끝", "배신", "붕괴"],
    light_keywords: ["완전한 종결"],
    shadow_keywords: ["절망"],
    love: ["관계 파탄"],
    career: ["직장 종료"],
    finance: ["큰 손실"],
    health: ["에너지 바닥"],
    spiritual: ["완전한 변화"],
    advice: ["끝을 받아들이고 새 시작을 준비하라"],
  },

  {
    id: 60,
    name: "Page of Swords",
    arcana: "minor",
    number: 11,
    core_keywords: ["호기심", "정보", "관찰"],
    light_keywords: ["학습", "분석"],
    shadow_keywords: ["소문", "경솔한 말"],
    love: ["관계 탐색"],
    career: ["정보 수집"],
    finance: ["시장 분석"],
    health: ["정신 활동 증가"],
    spiritual: ["지식 탐구"],
    advice: ["배움을 계속하라"],
  },

  {
    id: 61,
    name: "Knight of Swords",
    arcana: "minor",
    number: 12,
    core_keywords: ["속도", "행동", "결단"],
    light_keywords: ["결단력"],
    shadow_keywords: ["성급함", "충돌"],
    love: ["급격한 관계 전개"],
    career: ["강한 추진"],
    finance: ["위험한 결정"],
    health: ["과로"],
    spiritual: ["강한 의지"],
    advice: ["속도보다 방향을 확인하라"],
  },

  {
    id: 62,
    name: "Queen of Swords",
    arcana: "minor",
    number: 13,
    core_keywords: ["지혜", "독립", "명확성"],
    light_keywords: ["객관성", "통찰"],
    shadow_keywords: ["냉정함"],
    love: ["독립적 관계"],
    career: ["분석적 리더"],
    finance: ["합리적 관리"],
    health: ["정신적 강인함"],
    spiritual: ["진실 추구"],
    advice: ["감정과 이성을 균형 있게 사용하라"],
  },

  {
    id: 63,
    name: "King of Swords",
    arcana: "minor",
    number: 14,
    core_keywords: ["권위", "논리", "전략"],
    light_keywords: ["지적 리더십"],
    shadow_keywords: ["독단", "차가움"],
    love: ["이성적 관계"],
    career: ["전략적 리더"],
    finance: ["체계적 관리"],
    health: ["정신 집중"],
    spiritual: ["진리 탐구"],
    advice: ["논리와 공정함을 유지하라"],
  },
  // Pentacles
  {
    id: 64,
    name: "Ace of Pentacles",
    arcana: "minor",
    number: 1,
    core_keywords: ["새로운 기회", "물질적 시작", "안정"],
    light_keywords: ["번영", "현실적 기회"],
    shadow_keywords: ["기회 놓침"],
    love: ["안정적인 관계 시작"],
    career: ["새로운 직업 기회"],
    finance: ["재정 기회"],
    health: ["건강 회복 시작"],
    spiritual: ["현실 기반 성장"],
    advice: ["현실적인 기회를 잡아라"],
  },

  {
    id: 65,
    name: "Two of Pentacles",
    arcana: "minor",
    number: 2,
    core_keywords: ["균형", "우선순위", "유연성"],
    light_keywords: ["적응", "균형 유지"],
    shadow_keywords: ["혼란", "과부하"],
    love: ["관계와 일 균형"],
    career: ["다중 업무 관리"],
    finance: ["지출 관리"],
    health: ["생활 균형 필요"],
    spiritual: ["균형 찾기"],
    advice: ["우선순위를 정리하라"],
  },

  {
    id: 66,
    name: "Three of Pentacles",
    arcana: "minor",
    number: 3,
    core_keywords: ["협력", "기술", "팀워크"],
    light_keywords: ["협업 성공", "전문성"],
    shadow_keywords: ["협력 부족"],
    love: ["관계 노력"],
    career: ["팀 프로젝트 성공"],
    finance: ["안정적 성장"],
    health: ["전문 치료"],
    spiritual: ["배움"],
    advice: ["협력을 통해 성장하라"],
  },

  {
    id: 67,
    name: "Four of Pentacles",
    arcana: "minor",
    number: 4,
    core_keywords: ["보유", "안정", "통제"],
    light_keywords: ["재정 보호"],
    shadow_keywords: ["집착", "인색함"],
    love: ["감정적 소유"],
    career: ["안정 추구"],
    finance: ["저축"],
    health: ["안정 유지"],
    spiritual: ["집착 인식"],
    advice: ["붙잡기보다 흐름을 허용하라"],
  },

  {
    id: 68,
    name: "Five of Pentacles",
    arcana: "minor",
    number: 5,
    core_keywords: ["결핍", "어려움", "지원 필요"],
    light_keywords: ["도움 요청"],
    shadow_keywords: ["고립"],
    love: ["관계 어려움"],
    career: ["직업 불안"],
    finance: ["재정 어려움"],
    health: ["건강 약화"],
    spiritual: ["신념 시험"],
    advice: ["도움을 구하라"],
  },

  {
    id: 69,
    name: "Six of Pentacles",
    arcana: "minor",
    number: 6,
    core_keywords: ["나눔", "균형", "지원"],
    light_keywords: ["공정한 교환"],
    shadow_keywords: ["의존"],
    love: ["서로 돕는 관계"],
    career: ["지원 받음"],
    finance: ["재정 균형"],
    health: ["회복 도움"],
    spiritual: ["자비"],
    advice: ["주는 것과 받는 것을 균형 있게 하라"],
  },

  {
    id: 70,
    name: "Seven of Pentacles",
    arcana: "minor",
    number: 7,
    core_keywords: ["기다림", "평가", "장기 투자"],
    light_keywords: ["성장 과정"],
    shadow_keywords: ["인내 부족"],
    love: ["관계 평가"],
    career: ["성과 점검"],
    finance: ["장기 투자"],
    health: ["점진적 회복"],
    spiritual: ["성장 과정"],
    advice: ["인내심을 가져라"],
  },

  {
    id: 71,
    name: "Eight of Pentacles",
    arcana: "minor",
    number: 8,
    core_keywords: ["노력", "기술 향상", "집중"],
    light_keywords: ["성실함", "전문성"],
    shadow_keywords: ["과로"],
    love: ["관계 노력"],
    career: ["기술 발전"],
    finance: ["꾸준한 수입"],
    health: ["꾸준한 관리"],
    spiritual: ["수련"],
    advice: ["성실하게 계속 노력하라"],
  },

  {
    id: 72,
    name: "Nine of Pentacles",
    arcana: "minor",
    number: 9,
    core_keywords: ["독립", "풍요", "자립"],
    light_keywords: ["성취", "자신감"],
    shadow_keywords: ["고립"],
    love: ["독립적 관계"],
    career: ["개인 성공"],
    finance: ["재정 안정"],
    health: ["좋은 상태"],
    spiritual: ["자기 만족"],
    advice: ["자신의 성취를 즐겨라"],
  },

  {
    id: 73,
    name: "Ten of Pentacles",
    arcana: "minor",
    number: 10,
    core_keywords: ["장기 안정", "가족 재산", "완성"],
    light_keywords: ["풍요", "지속성"],
    shadow_keywords: ["전통 집착"],
    love: ["가족 중심 관계"],
    career: ["장기 성공"],
    finance: ["부와 안정"],
    health: ["안정 상태"],
    spiritual: ["세대 연결"],
    advice: ["장기적인 안정을 구축하라"],
  },

  {
    id: 74,
    name: "Page of Pentacles",
    arcana: "minor",
    number: 11,
    core_keywords: ["학습", "새로운 기회", "실용성"],
    light_keywords: ["호기심", "성장"],
    shadow_keywords: ["미숙함"],
    love: ["관계 발전 가능성"],
    career: ["새로운 공부 시작"],
    finance: ["재정 학습"],
    health: ["건강 습관 시작"],
    spiritual: ["배움"],
    advice: ["배움을 시작하라"],
  },

  {
    id: 75,
    name: "Knight of Pentacles",
    arcana: "minor",
    number: 12,
    core_keywords: ["성실함", "책임", "꾸준함"],
    light_keywords: ["신뢰", "안정"],
    shadow_keywords: ["지루함", "느림"],
    love: ["안정적 관계"],
    career: ["꾸준한 노력"],
    finance: ["안정적 수입"],
    health: ["규칙적 관리"],
    spiritual: ["성실한 성장"],
    advice: ["꾸준함을 유지하라"],
  },

  {
    id: 76,
    name: "Queen of Pentacles",
    arcana: "minor",
    number: 13,
    core_keywords: ["돌봄", "안정", "실용성"],
    light_keywords: ["풍요", "현실적 지혜"],
    shadow_keywords: ["과보호"],
    love: ["안정적인 파트너"],
    career: ["관리 능력"],
    finance: ["현명한 재정"],
    health: ["균형 잡힌 생활"],
    spiritual: ["자연 연결"],
    advice: ["안정을 기반으로 성장하라"],
  },

  {
    id: 77,
    name: "King of Pentacles",
    arcana: "minor",
    number: 14,
    core_keywords: ["부", "안정", "리더십"],
    light_keywords: ["현실적 성공", "책임"],
    shadow_keywords: ["물질 집착"],
    love: ["신뢰 가능한 파트너"],
    career: ["사업 성공"],
    finance: ["큰 재정 안정"],
    health: ["강한 체력"],
    spiritual: ["현실 기반 지혜"],
    advice: ["책임 있게 자원을 관리하라"],
  },
];
