/**
 * 카드-상황 조합의 기본 영향 가중치를 정의합니다.
 */
export const SITUATION_WEIGHT = [
  {
    cardId: 0,
    base: {
      love: 0.4,
      career: 0.5,
      money: 0.3,
      health: 0.4,
      personal: 0.9,
      spiritual: 0.8,
    },
  },
  // 메이저 아르카나
  {
    cardId: 1,
    base: {
      love: 0.5,
      career: 0.8,
      money: 0.6,
      health: 0.4,
      personal: 0.6,
      spiritual: 0.7,
    },
  },
  {
    cardId: 2,
    base: {
      love: 0.6,
      career: 0.3,
      money: 0.3,
      health: 0.4,
      personal: 0.6,
      spiritual: 0.9,
    },
  },
  {
    cardId: 3,
    base: {
      love: 0.8,
      career: 0.5,
      money: 0.6,
      health: 0.6,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 4,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.7,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.4,
    },
  },
  {
    cardId: 5,
    base: {
      love: 0.5,
      career: 0.5,
      money: 0.4,
      health: 0.4,
      personal: 0.6,
      spiritual: 0.9,
    },
  },
  {
    cardId: 6,
    base: {
      love: 0.95,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 7,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.6,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  {
    cardId: 8,
    base: {
      love: 0.4,
      career: 0.6,
      money: 0.5,
      health: 0.7,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 9,
    base: {
      love: 0.4,
      career: 0.3,
      money: 0.3,
      health: 0.5,
      personal: 0.8,
      spiritual: 0.9,
    },
  },
  {
    cardId: 10,
    base: {
      love: 0.6,
      career: 0.6,
      money: 0.6,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.6,
    },
  },
  {
    cardId: 11,
    base: {
      love: 0.6,
      career: 0.7,
      money: 0.6,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.5,
    },
  },
  {
    cardId: 12,
    base: {
      love: 0.5,
      career: 0.3,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.8,
    },
  },
  {
    cardId: 13,
    base: {
      love: 0.7,
      career: 0.5,
      money: 0.4,
      health: 0.6,
      personal: 0.8,
      spiritual: 0.7,
    },
  },
  {
    cardId: 14,
    base: {
      love: 0.7,
      career: 0.6,
      money: 0.5,
      health: 0.8,
      personal: 0.7,
      spiritual: 0.7,
    },
  },
  {
    cardId: 15,
    base: {
      love: 0.8,
      career: 0.6,
      money: 0.6,
      health: 0.4,
      personal: 0.7,
      spiritual: 0.4,
    },
  },
  {
    cardId: 16,
    base: {
      love: 0.6,
      career: 0.6,
      money: 0.6,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.5,
    },
  },
  {
    cardId: 17,
    base: {
      love: 0.8,
      career: 0.5,
      money: 0.4,
      health: 0.6,
      personal: 0.7,
      spiritual: 0.8,
    },
  },
  {
    cardId: 18,
    base: {
      love: 0.7,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.8,
      spiritual: 0.7,
    },
  },
  {
    cardId: 19,
    base: {
      love: 0.8,
      career: 0.7,
      money: 0.6,
      health: 0.7,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 20,
    base: {
      love: 0.6,
      career: 0.6,
      money: 0.5,
      health: 0.6,
      personal: 0.8,
      spiritual: 0.8,
    },
  },
  {
    cardId: 21,
    base: {
      love: 0.8,
      career: 0.7,
      money: 0.6,
      health: 0.7,
      personal: 0.7,
      spiritual: 0.7,
    },
  },
  // 마이너 아르카나
  // 완드
  {
    cardId: 22,
    base: {
      love: 0.5,
      career: 0.7,
      money: 0.4,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  {
    cardId: 23,
    base: {
      love: 0.6,
      career: 0.7,
      money: 0.4,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  {
    cardId: 24,
    base: {
      love: 0.6,
      career: 0.8,
      money: 0.5,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  {
    cardId: 25,
    base: {
      love: 0.5,
      career: 0.7,
      money: 0.4,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  {
    cardId: 26,
    base: {
      love: 0.6,
      career: 0.7,
      money: 0.5,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  {
    cardId: 27,
    base: {
      love: 0.6,
      career: 0.8,
      money: 0.6,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  {
    cardId: 28,
    base: {
      love: 0.5,
      career: 0.7,
      money: 0.5,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  {
    cardId: 29,
    base: {
      love: 0.5,
      career: 0.7,
      money: 0.4,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  {
    cardId: 30,
    base: {
      love: 0.6,
      career: 0.8,
      money: 0.5,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  {
    cardId: 31,
    base: {
      love: 0.6,
      career: 0.7,
      money: 0.4,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  {
    cardId: 32,
    base: {
      love: 0.6,
      career: 0.7,
      money: 0.4,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  {
    cardId: 33,
    base: {
      love: 0.5,
      career: 0.7,
      money: 0.4,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  {
    cardId: 34,
    base: {
      love: 0.6,
      career: 0.8,
      money: 0.5,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  {
    cardId: 35,
    base: {
      love: 0.7,
      career: 0.7,
      money: 0.5,
      health: 0.5,
      personal: 0.6,
      spiritual: 0.4,
    },
  },
  // 컵
  {
    cardId: 36,
    base: {
      love: 0.9,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 37,
    base: {
      love: 0.9,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 38,
    base: {
      love: 0.8,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 39,
    base: {
      love: 0.9,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 40,
    base: {
      love: 0.9,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 41,
    base: {
      love: 0.8,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 42,
    base: {
      love: 0.8,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 43,
    base: {
      love: 0.8,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 44,
    base: {
      love: 0.9,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 45,
    base: {
      love: 0.8,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 46,
    base: {
      love: 0.9,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 47,
    base: {
      love: 0.8,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 48,
    base: {
      love: 0.9,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  {
    cardId: 49,
    base: {
      love: 0.9,
      career: 0.4,
      money: 0.3,
      health: 0.5,
      personal: 0.7,
      spiritual: 0.6,
    },
  },
  // 소드
  {
    cardId: 50,
    base: {
      love: 0.5,
      career: 0.6,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.5,
    },
  },
  {
    cardId: 51,
    base: {
      love: 0.5,
      career: 0.6,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.5,
    },
  },
  {
    cardId: 52,
    base: {
      love: 0.5,
      career: 0.6,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.5,
    },
  },
  {
    cardId: 53,
    base: {
      love: 0.5,
      career: 0.6,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.5,
    },
  },
  {
    cardId: 54,
    base: {
      love: 0.4,
      career: 0.6,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.5,
    },
  },
  {
    cardId: 55,
    base: {
      love: 0.4,
      career: 0.6,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.5,
    },
  },
  {
    cardId: 56,
    base: {
      love: 0.4,
      career: 0.6,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.5,
    },
  },
  {
    cardId: 57,
    base: {
      love: 0.4,
      career: 0.6,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.5,
    },
  },
  {
    cardId: 58,
    base: {
      love: 0.5,
      career: 0.6,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.5,
    },
  },
  {
    cardId: 59,
    base: {
      love: 0.5,
      career: 0.6,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.5,
    },
  },
  {
    cardId: 60,
    base: {
      love: 0.5,
      career: 0.6,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.5,
    },
  },
  {
    cardId: 61,
    base: {
      love: 0.5,
      career: 0.6,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.5,
    },
  },
  {
    cardId: 62,
    base: {
      love: 0.4,
      career: 0.6,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.5,
    },
  },
  {
    cardId: 63,
    base: {
      love: 0.4,
      career: 0.6,
      money: 0.3,
      health: 0.4,
      personal: 0.8,
      spiritual: 0.5,
    },
  },
  // 펜타클
  {
    cardId: 64,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.9,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.3,
    },
  },
  {
    cardId: 65,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.9,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.3,
    },
  },
  {
    cardId: 66,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.9,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.3,
    },
  },
  {
    cardId: 67,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.9,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.3,
    },
  },
  {
    cardId: 68,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.9,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.3,
    },
  },
  {
    cardId: 69,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.9,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.3,
    },
  },
  {
    cardId: 70,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.9,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.3,
    },
  },
  {
    cardId: 71,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.9,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.3,
    },
  },
  {
    cardId: 72,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.9,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.3,
    },
  },
  {
    cardId: 73,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.9,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.3,
    },
  },
  {
    cardId: 74,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.9,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.3,
    },
  },
  {
    cardId: 75,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.9,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.3,
    },
  },
  {
    cardId: 76,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.9,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.3,
    },
  },
  {
    cardId: 77,
    base: {
      love: 0.4,
      career: 0.8,
      money: 0.9,
      health: 0.5,
      personal: 0.5,
      spiritual: 0.3,
    },
  },
];



